
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Radiobutton, StringVar
import sys
import json


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\checkout\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def run_checkout(cart_items):
    window = Tk()
    window.geometry("399x528")
    window.configure(bg="#FFF8E7")
    canvas = Canvas(
        window,
        bg="#FFF8E7",
        height=528,
        width=399,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    canvas.create_text(
        37.0, 28.0, anchor="nw", text="Checkout", fill="#000000", font=("Poppins Bold", 20 * -1)
    )
    # Order summary text
    order_lines = []
    subtotal = 0
    for item in cart_items:
        qty = item.get("qty", 1)
        name = item.get("name", "?")
        size = item.get("size", "Regular")
        price = float(item.get("price", 0))
        order_lines.append(f"- {name} ({size}) x {qty} ₱{price * qty:,.2f}")
        subtotal += price * qty
    summary = "\n".join(order_lines)
    summary += f"\n\nSubtotal: ₱{subtotal:,.2f}\nTotal: ₱{subtotal:,.2f}\n\nPayment:"  # assuming no add-ons
    canvas.create_text(
        39.0, 75.0, anchor="nw", text=summary, fill="#1E1E1E", font=("Inter", 16 * -1)
    )
    # Payment method (radio buttons) - exclusive (cannot unselect all)
    pay_method = StringVar(value="Cash")
    y_base = 220
    methods = ["Cash", "GCash", "Card (Visa/Mastercard)"]
    for idx, txt in enumerate(methods):
        rb = Radiobutton(
            window, text=txt, variable=pay_method, value=txt,
            anchor="w", font=("Inter", 16 * -1), bg="#FFF8E7"
        )
        rb.place(x=80, y=y_base + 31*idx)
    # button_1 = Close
    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
    def close_window():
        window.destroy()
    button_1 = Button(
        image=button_image_1, borderwidth=0,
        highlightthickness=0, command=close_window, relief="flat"
    )
    button_1.place(
        x=193.0, y=472.0, width=90.61764526367188, height=39.73057174682617
    )
    # button_2 = Confirm
    button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
    def confirm_action():
        import tkinter.messagebox as mbox
        if not pay_method.get():
            mbox.showinfo("Select Payment", "Please select a payment method.")
            return
        mbox.showinfo("Checkout", f"Order confirmed! Payment: {pay_method.get()}")
        window.destroy()
    button_2 = Button(
        image=button_image_2, borderwidth=0,
        highlightthickness=0, command=confirm_action, relief="flat"
    )
    button_2.place(
        x=292.0, y=472.0, width=93.60504150390625, height=39.73057174682617
    )
    window.resizable(False, False)
    window.mainloop()
# Only run if executed as script for testing demo
if __name__ == "__main__":
    cart = None
    if len(sys.argv) > 1:
        try:
            # Read cart from temp file passed as command line argument
            with open(sys.argv[1], 'r') as f:
                cart = json.load(f)
        except Exception as ex:
            print("Failed to read order cart for checkout:", ex)
            cart = None
    if cart is None:
        cart = [{'name': 'Chocolate', 'size': 'Regular', 'price': 29.00, 'qty': 1}]
    run_checkout(cart)
