
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os
import sys
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("resources/coming_soon")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
# Center the window on the screen
try:
    window.update_idletasks()
    _w, _h = 1035, 530
    _sw = window.winfo_screenwidth()
    _sh = window.winfo_screenheight()
    _x = int((_sw - _w) / 2)
    _y = int((_sh - _h) / 2)
    window.geometry(f"{_w}x{_h}+{_x}+{_y}")
except Exception:
    window.geometry("1035x530")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 530,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    517.0,
    267.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    1035.0,
    60.0,
    fill="#B96708",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    89.0,
    29.0,
    image=image_image_2
)

canvas.create_rectangle(
    0.0,
    56.0,
    1035.0,
    534.0,
    fill="#EFE8D8",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    886.0,
    288.0,
    image=image_image_3
)

# -------- Navigation helpers --------
def _open_script(script_name: str):
    try:
        script_path = os.path.join(os.path.dirname(__file__), script_name)
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass

def open_order():
    _open_script("order.py")

def open_menu_coffee():
    _open_script("menu_coffee.py")

def go_back_previous():
    # Try env var BIGBREW_PREV for previous script; else fallback to home.py
    prev = os.environ.get("BIGBREW_PREV", "home.py")
    if not prev.endswith(".py"):
        prev = f"{prev}.py"
    _open_script(prev)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: None,
    state="disabled",
    relief="flat"
)
button_1.place(
    x=788.911865234375,
    y=447.12646484375,
    width=90.61764526367188,
    height=39.73057174682617
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: None,
    state="disabled",
    relief="flat"
)
button_2.place(
    x=893.470703125,
    y=447.12646484375,
    width=93.60504150390625,
    height=39.73057174682617
)

canvas.create_text(
    796.878173828125,
    372.86761474609375,
    anchor="nw",
    text="Add-On",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.0,
    371.0,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    353.0023193359375,
    anchor="nw",
    text="SubTotal",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.2900390625,
    350.3536376953125,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.2900390625,
    414.5302429199219,
    anchor="nw",
    text="₱0.00",
    fill="#1E1E1E",
    font=("Poppins SemiBold", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    412.59820556640625,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("Poppins SemiBold", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    135.0,
    288.0,
    image=image_image_4
)

canvas.create_text(
    58.0,
    81.0,
    anchor="nw",
    text="Menu",
    fill="#B96708",
    font=("Poppins ExtraBold", 32 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=49.0,
    y=435.0,
    width=171.0,
    height=35.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=49.0,
    y=387.0,
    width=171.0,
    height=35.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_menu_coffee,
    relief="flat"
)
button_5.place(
    x=49.0,
    y=338.0,
    width=171.0,
    height=36.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=49.0,
    y=290.0,
    width=171.0,
    height=35.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=49.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=49.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=open_order,
    relief="flat"
)
button_9.place(
    x=49.0,
    y=193.0,
    width=171.0,
    height=35.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=49.0,
    y=144.0,
    width=171.0,
    height=36.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=go_back_previous,
    relief="flat"
)
button_11.place(
    x=944.0,
    y=0.0,
    width=46.0,
    height=46.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    495.0,
    288.0,
    image=image_image_5
)

canvas.create_text(
    318.0,
    446.0,
    anchor="nw",
    text="Coming Soon!",
    fill="#A89C88",
    font=("Poppins ExtraBold", 48 * -1)
)
window.resizable(False, False)
window.mainloop()
