# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox
import mysql.connector
from utils import UtilityFunctions, EmailService
from otp import OTPVerificationWindow
import sys
import os

OUTPUT_PATH = Path(__file__).parent

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    
    return os.path.join(base_path, relative_path)

def relative_to_assets(path: str) -> Path:
    return Path(resource_path(f"resources/forgotpass/{path}"))

class ForgotPasswordWindow:
    def __init__(self, parent, show_login_callback, get_db_connection):
        self.parent = parent
        self.show_login_callback = show_login_callback
        self.get_db_connection = get_db_connection
        self.otp_code = None
        self.user_email = None
        
        self.setup_ui()
        
    def setup_ui(self):
        self.canvas = Canvas(
            self.parent,
            bg="#FFFFFF",
            height=440,
            width=800,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)
        
        # Background image
        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            400.0,
            220.0,
            image=self.image_image_1
        )

        # Title background rectangle
        self.canvas.create_rectangle(
            110.0,
            124.0,
            247.0,
            140.0,
            fill="#3A280F",
            outline="")

        # Reset password button
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_resetpass.png"))
        self.button_resetpass = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.send_reset_email,
            relief="flat"
        )
        self.button_resetpass.place(
            x=54.0,
            y=323.0,
            width=245.0,
            height=42.0
        )

        # Title background rectangle
        self.canvas.create_rectangle(
            100.0,
            87.0,
            255.0,
            132.0,
            fill="#3A280F",
            outline="")

        # Title text
        self.canvas.create_text(
            31.0,
            89.0,
            anchor="nw",
            text="Forgot Password",
            fill="#FFFFFF",
            font=("Inter Bold", 36 * -1)
        )

        # Email input background rectangle
        self.canvas.create_rectangle(
            18.0,
            154.0,
            336.0,
            286.0,
            fill="#3A280F",
            outline="")

        # Email entry field
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_email.png"))
        self.entry_bg_1 = self.canvas.create_image(
            177.0,
            235.0,
            image=self.entry_image_1
        )
        self.entry_email = Entry(
            bd=0,
            bg="#FFF8E7",
            fg="#000716",
            highlightthickness=0,
            font=("Inter", 12)
        )
        self.entry_email.place(
            x=38.0,
            y=215.0,
            width=278.0,
            height=38.0
        )
        self.entry_email.bind('<Return>', lambda e: self.send_reset_email())

        # Email label
        self.canvas.create_text(
            30.0,
            184.0,
            anchor="nw",
            text="Email Address:",
            fill="#FFFFFF",
            font=("Inter Bold", 16 * -1)
        )

        # Back button - create after all other elements
        try:
            button_back_1 = PhotoImage(
                file=relative_to_assets("button_back.png"))
            button_back = Button(
                image=button_back_1,
                borderwidth=0,
                highlightthickness=0,
                command=self.go_back,
                relief="flat",
                cursor="hand2"
            )
            button_back.place(
                x=10.0,
                y=10.0,
                width=30.0,
                height=30.0
            )
            # Ensure back button is on top of all other elements
            button_back.lift()
            # Store reference to prevent garbage collection
            self.button_back_image = button_back_1
        except Exception as e:
            print(f"Error loading back button image: {e}")
            # Fallback: create text button if image fails
            button_back = Button(
                text="←",
                borderwidth=0,
                highlightthickness=0,
                command=self.go_back,
                relief="flat",
                cursor="hand2",
                bg="#3A280F",
                fg="#FFFFFF",
                font=("Arial", 12, "bold")
            )
            button_back.place(
                x=10.0,
                y=10.0,
                width=30.0,
                height=30.0
            )
            button_back.lift()

    def send_reset_email(self):
        """Send password reset OTP email"""
        email = self.entry_email.get().strip()
        
        if not email:
            messagebox.showerror("Error", "Please enter your email address")
            return
            
        if not UtilityFunctions.is_valid_email(email):
            messagebox.showerror("Error", "Please enter a valid email address")
            return

        db_connection = self.get_db_connection()
        if not db_connection:
            messagebox.showerror("Database Error", "Cannot connect to database")
            return

        try:
            cursor = db_connection.cursor(dictionary=True)
            
            # Check if email exists in customers table (not users table)
            cursor.execute("SELECT customer_id, email FROM customers WHERE email = %s AND is_active = 1", (email,))
            customer = cursor.fetchone()

            if not customer:
                messagebox.showerror("Error", "No account found with this email address")
                return

            # Generate OTP
            self.otp_code = UtilityFunctions.generate_otp()
            self.user_email = email
            
            # Store OTP in database for verification tracking
            from datetime import datetime, timedelta
            expires_at = datetime.now() + timedelta(minutes=3)
            
            # Clean up any existing OTP for this email and purpose
            cursor.execute("DELETE FROM otp_verification WHERE email = %s AND purpose = %s", (email, 'password_reset'))
            
            cursor.execute("""
                INSERT INTO otp_verification (email, otp_code, purpose, expires_at)
                VALUES (%s, %s, %s, %s)
            """, (email, self.otp_code, 'password_reset', expires_at))
            
            db_connection.commit()

            # Send OTP email
            email_service = EmailService()
            try:
                if email_service.send_otp_email(email, self.otp_code):
                    self.show_otp_verification()
                else:
                    messagebox.showerror("Error", "Failed to send OTP email. Please check your email configuration or try again later.")
            except Exception as email_error:
                print(f"Email sending error: {email_error}")
                messagebox.showerror("Email Error", f"Failed to send verification email: {str(email_error)}")
                return

        except Exception as e:
            messagebox.showerror("Error", f"Failed to process request: {str(e)}")
        finally:
            if db_connection and db_connection.is_connected():
                cursor.close()

    def show_otp_verification(self):
        """Show OTP verification for password reset"""
        user_data = {'email': self.user_email}
        
        self.destroy()
        OTPVerificationWindow(
            self.parent,
            user_data,
            self.otp_code,
            self.show_password_reset,
            self.show_login_callback,
            self.get_db_connection,
            purpose='password_reset'
        )

    def show_password_reset(self):
        """Show password reset screen after OTP verification"""
        from resetpass import PasswordResetWindow
        self.destroy()
        PasswordResetWindow(
            self.parent,
            self.user_email,
            self.show_login_callback,
            self.get_db_connection
        )

    def go_back(self):
        """Return to login screen"""
        self.destroy()
        self.show_login_callback()

    def destroy(self):
        """Clean up the window"""
        for widget in self.parent.winfo_children():
            widget.destroy()
