
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\output tk\bnyes\1\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x440")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 440,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    400.0,
    220.0,
    image=image_image_1
)

canvas.create_rectangle(
    110.0,
    124.0,
    247.0,
    140.0,
    fill="#3A280F",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_resetpass.png"))
button_resetpass = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_resetpass clicked"),
    relief="flat"
)
button_resetpass.place(
    x=54.0,
    y=323.0,
    width=245.0,
    height=42.0
)

canvas.create_rectangle(
    100.0,
    87.0,
    255.0,
    132.0,
    fill="#3A280F",
    outline="")

canvas.create_text(
    31.0,
    89.0,
    anchor="nw",
    text="Forgot Password",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

canvas.create_rectangle(
    18.0,
    154.0,
    336.0,
    286.0,
    fill="#3A280F",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_email.png"))
entry_bg_1 = canvas.create_image(
    177.0,
    235.0,
    image=entry_image_1
)
entry_email = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_email.place(
    x=38.0,
    y=215.0,
    width=278.0,
    height=38.0
)

canvas.create_text(
    30.0,
    184.0,
    anchor="nw",
    text="Email Address:",
    fill="#FFFFFF",
    font=("Inter Bold", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
