
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\coffee\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
# Center the window on the screen
try:
    window.update_idletasks()
    _w, _h = 1035, 534
    _sw = window.winfo_screenwidth()
    _sh = window.winfo_screenheight()
    _x = int((_sw - _w) / 2)
    _y = int((_sh - _h) / 2)
    window.geometry(f"{_w}x{_h}+{_x}+{_y}")
except Exception:
    pass
# window.geometry("1035x534")  # Disabled to use centered geometry
window.configure(bg = "#FFFFFF")

# --- Add window switching functions like order.py ---
import os
import sys
import subprocess

def open_home():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "home.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass

def open_coming_soon():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "coming_soon.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass

def open_order():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "order.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 534,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    517.0,
    267.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    57.0,
    1035.0,
    535.0,
    fill="#EFE8D8",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1035.0,
    57.0,
    fill="#B96708",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_home,
    relief="flat"
)
button_1.place(
    x=944.0,
    y=0.0,
    width=46.0,
    height=46.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    94.0,
    28.0,
    image=image_image_2
)

canvas.create_rectangle(
    34.0,
    75.0,
    236.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    135.0,
    288.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    501.0,
    287.0,
    image=image_image_4
)

canvas.create_text(
    58.0,
    81.0,
    anchor="nw",
    text="Menu",
    fill="#B96708",
    font=("Poppins Black", 32 * -1)
)

canvas.create_text(
    268.0,
    90.0,
    anchor="nw",
    text="Coffee",
    fill="#B96708",
    font=("Poppins Bold", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_2.place(
    x=51.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_order,
    relief="flat"
)
button_3.place(
    x=49.0,
    y=189.0,
    width=171.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_4.place(
    x=49.0,
    y=136.0,
    width=171.0,
    height=36.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_5.place(
    x=51.0,
    y=290.0,
    width=171.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=51.0,
    y=338.0,
    width=171.0,
    height=36.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_7.place(
    x=51.0,
    y=387.0,
    width=171.0,
    height=35.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_8.place(
    x=51.0,
    y=435.0,
    width=171.0,
    height=35.0
)

canvas.create_rectangle(
    768.0,
    75.0,
    1005.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    886.0,
    288.0,
    image=image_image_5
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=788.911865234375,
    y=447.12646484375,
    width=90.61764526367188,
    height=39.73057174682617
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=893.470703125,
    y=447.12646484375,
    width=93.60504150390625,
    height=39.73057174682617
)

canvas.create_text(
    796.878173828125,
    372.86761474609375,
    anchor="nw",
    text="Add-On",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.0,
    371.0,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    353.0023193359375,
    anchor="nw",
    text="SubTotal",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.2900390625,
    350.3536376953125,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.2900390625,
    414.5302734375,
    anchor="nw",
    text="₱0.00",
    fill="#1E1E1E",
    font=("Poppins SemiBold", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    412.59820556640625,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("Poppins SemiBold", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    302.0,
    28.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=205.5,
    y=9.0,
    width=193.0,
    height=37.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=367.0,
    y=131.0,
    width=78.0,
    height=133.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=463.0,
    y=131.0,
    width=78.0,
    height=133.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=271.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=557.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_15 clicked"),
    relief="flat"
)
button_15.place(
    x=653.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_16 clicked"),
    relief="flat"
)
button_16.place(
    x=271.0,
    y=281.0,
    width=77.0,
    height=133.0
)

button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_17 clicked"),
    relief="flat"
)
button_17.place(
    x=366.0,
    y=281.0,
    width=78.0,
    height=133.0
)

button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_18 clicked"),
    relief="flat"
)
button_18.place(
    x=463.0,
    y=282.0,
    width=77.0,
    height=132.0
)

canvas.create_rectangle(
    734.0,
    132.0,
    746.0,
    196.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
