
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame, Scrollbar
from pop_up import show_options_popup  # Add this import
from tkinter import messagebox  # Add this import after existing imports
import tempfile
import os
import sys
import subprocess
import json


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\coffee\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
# Center the window on the screen
try:
    window.update_idletasks()
    _w, _h = 1035, 534
    _sw = window.winfo_screenwidth()
    _sh = window.winfo_screenheight()
    _x = int((_sw - _w) / 2)
    _y = int((_sh - _h) / 2)
    window.geometry(f"{_w}x{_h}+{_x}+{_y}")
except Exception:
    pass
# window.geometry("1035x534")  # Disabled to use centered geometry
window.configure(bg = "#FFFFFF")

# --- Add window switching functions like order.py ---


def open_home():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "home.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass

def open_coming_soon():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "coming_soon.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass

def open_order():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "order.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 534,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    517.0,
    267.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    57.0,
    1035.0,
    535.0,
    fill="#EFE8D8",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1035.0,
    57.0,
    fill="#B96708",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_home,
    relief="flat"
)
button_1.place(
    x=944.0,
    y=0.0,
    width=46.0,
    height=46.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    94.0,
    28.0,
    image=image_image_2
)

canvas.create_rectangle(
    34.0,
    75.0,
    236.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    135.0,
    288.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    501.0,
    287.0,
    image=image_image_4
)

canvas.create_text(
    58.0,
    81.0,
    anchor="nw",
    text="Menu",
    fill="#B96708",
    font=("Poppins Black", 32 * -1)
)

canvas.create_text(
    268.0,
    90.0,
    anchor="nw",
    text="Coffee",
    fill="#B96708",
    font=("Poppins Bold", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_2.place(
    x=51.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=open_order,
    relief="flat"
)
button_3.place(
    x=49.0,
    y=189.0,
    width=171.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_4.place(
    x=49.0,
    y=136.0,
    width=171.0,
    height=36.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_5.place(
    x=51.0,
    y=290.0,
    width=171.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=51.0,
    y=338.0,
    width=171.0,
    height=36.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_7.place(
    x=51.0,
    y=387.0,
    width=171.0,
    height=35.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_8.place(
    x=51.0,
    y=435.0,
    width=171.0,
    height=35.0
)

canvas.create_rectangle(
    768.0,
    75.0,
    1005.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    886.0,
    288.0,
    image=image_image_5
)

# --- Scrollable cart area (only for cart items; totals remain fixed) ---
cart_container = Frame(window, bg="#EFE8D8")
cart_container.place(x=772, y=120, width=225, height=220)

cart_scrollbar = Scrollbar(cart_container, orient="vertical")
cart_scrollbar.pack(side="right", fill="y")

cart_canvas = Canvas(
    cart_container,
    bg="#EFE8D8",
    bd=0,
    highlightthickness=0,
    yscrollcommand=cart_scrollbar.set,
)
cart_canvas.pack(side="left", fill="both", expand=True)
cart_scrollbar.config(command=cart_canvas.yview)

# Mouse wheel scrolling only when pointer is over the cart canvas
def _on_cart_mousewheel(event):
    try:
        cart_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
    except Exception:
        pass

def _bind_cart_wheel(_event=None):
    try:
        cart_canvas.bind_all("<MouseWheel>", _on_cart_mousewheel)
    except Exception:
        pass

def _unbind_cart_wheel(_event=None):
    try:
        cart_canvas.unbind_all("<MouseWheel>")
    except Exception:
        pass

cart_canvas.bind("<Enter>", _bind_cart_wheel)
cart_canvas.bind("<Leave>", _unbind_cart_wheel)

# -------------- Cart state, add, and render, matching order.py -------------------
cart_items = []  # Each: {name, size, price, qty}
cart_item_canvas_ids = []
add_on_total_amount = 0.0
_add_on_amount_text_id = None
_subtotal_amount_text_id = None
_total_amount_text_id = None

def abbreviate_text(text, max_chars=24):
    try:
        if len(text) <= max_chars:
            return text
        return text[: max_chars - 1] + "…"
    except Exception:
        return text

def add_item_to_cart(item):
    global add_on_total_amount
    # Treat add-ons as amount-only; don't add a cart line
    if item.get('is_add_on'):
        try:
            add_on_total_amount += float(item.get('price', 0)) * int(item.get('qty', 1))
        except Exception:
            pass
        render_cart()
        return
    # If same name+size+price exists, increment qty; else append
    for it in cart_items:
        if (
            it['name'] == item['name'] and 
            it.get('size','Regular') == item.get('size','Regular') and 
            float(it.get('price',0)) == float(item.get('price',0))
        ):
            it['qty'] += item.get('qty', 1)
            break
    else:
        cart_items.append({
            'name': item['name'],
            'size': item.get('size','Regular'),
            'price': float(item['price']),
            'qty': int(item.get('qty',1)),
            'is_add_on': item.get('is_add_on', False)
        })
    render_cart()

def change_item_qty(idx, delta):
    if 0 <= idx < len(cart_items):
        cart_items[idx]['qty'] = max(0, cart_items[idx]['qty'] + delta)
        if cart_items[idx]['qty'] == 0:
            del cart_items[idx]
        render_cart()

def render_cart():
    # Clear only the cart items canvas, not the main canvas
    for cid in cart_item_canvas_ids:
        try:
            cart_canvas.delete(cid)
        except:
            pass
    cart_item_canvas_ids.clear()

    # Local coordinates inside the cart_canvas
    left_x, right_x = 10, 215
    y, card_height, v_gap = 0, 70, 14
    for idx, it in enumerate(cart_items):
        # Card bg
        bg = cart_canvas.create_rectangle(
            left_x, y, right_x, y + card_height, fill="#ECE3D1", outline="", width=0
        )
        cart_item_canvas_ids.append(bg)
        # Name (Size)
        full_title = f"{it['name']}  ({it.get('size','Regular')})"
        title = abbreviate_text(full_title, 24)
        t1 = cart_canvas.create_text(
            left_x + 16,
            y + 12,
            anchor="nw",
            text=title,
            fill="#1E1E1E",
            font=("Poppins SemiBold", 11 * -1),
        )
        cart_item_canvas_ids.append(t1)
        # Price right
        price_str = f"₱{it['price']:.2f}"
        tprice = cart_canvas.create_text(
            right_x - 16,
            y + 12,
            anchor="ne",
            text=price_str,
            fill="#1E1E1E",
            font=("Poppins SemiBold", 12 * -1),
        )
        cart_item_canvas_ids.append(tprice)
        # Qty line
        qty_line = f"{it['qty']}  x  ₱{it['price']:.2f}"
        t2 = cart_canvas.create_text(
            left_x + 16,
            y + 36,
            anchor="nw",
            text=qty_line,
            fill="#9A9A9B",
            font=("Poppins Regular", 11 * -1),
        )
        cart_item_canvas_ids.append(t2)
        # Minus
        minus_circ = cart_canvas.create_oval(
            right_x - 64, y + 36, right_x - 40, y + 60, outline="#9A9A9B", width=2
        )
        minus_line = cart_canvas.create_line(
            right_x - 60, y + 48, right_x - 44, y + 48, fill="#9A9A9B", width=2
        )
        cart_item_canvas_ids.extend([minus_circ, minus_line])
        # Plus
        plus_circ = cart_canvas.create_oval(
            right_x - 32, y + 36, right_x - 8, y + 60, outline="#9A9A9B", width=2
        )
        plus_h = cart_canvas.create_line(
            right_x - 28, y + 48, right_x - 12, y + 48, fill="#9A9A9B", width=2
        )
        plus_v = cart_canvas.create_line(
            right_x - 20, y + 40, right_x - 20, y + 56, fill="#9A9A9B", width=2
        )
        cart_item_canvas_ids.extend([plus_circ, plus_h, plus_v])
        # Bind add/subtract
        def bind_click(tag_id, cb):
            cart_canvas.tag_bind(tag_id, "<Button-1>", lambda _e: cb())
        bind_click(minus_circ, lambda i=idx: change_item_qty(i, -1))
        bind_click(minus_line, lambda i=idx: change_item_qty(i, -1))
        bind_click(plus_circ, lambda i=idx: change_item_qty(i, +1))
        bind_click(plus_h, lambda i=idx: change_item_qty(i, +1))
        bind_click(plus_v, lambda i=idx: change_item_qty(i, +1))
        y += card_height + v_gap
    # Update scrollable area
    try:
        cart_canvas.configure(scrollregion=(0, 0, 225, y))
    except Exception:
        pass
    update_totals()

def update_totals():
    try:
        subtotal = 0.0
        for it in cart_items:
            if not it.get('is_add_on'):
                subtotal += float(it.get('price', 0)) * int(it.get('qty', 1))
        total = subtotal + add_on_total_amount
        if _add_on_amount_text_id is not None:
            canvas.itemconfigure(_add_on_amount_text_id, text=f"₱{add_on_total_amount:.2f}")
        if _subtotal_amount_text_id is not None:
            canvas.itemconfigure(_subtotal_amount_text_id, text=f"₱{subtotal:.2f}")
        if _total_amount_text_id is not None:
            canvas.itemconfigure(_total_amount_text_id, text=f"₱{total:.2f}")
    except Exception:
        pass

def clear_cart():
    global add_on_total_amount
    try:
        cart_items.clear()
        add_on_total_amount = 0.0
        render_cart()
    except Exception:
        pass

def checkout_cart():
    if not cart_items:
        try:
            messagebox.showinfo("Checkout", "Your cart is empty.")
        except Exception:
            pass
        return
    # Write cart_items to a temp file
    with tempfile.NamedTemporaryFile(delete=False, mode="w", suffix=".json") as tf:
        try:
            export_items = list(cart_items)
            # Add a single consolidated Add-On line for checkout to match totals
            if add_on_total_amount and add_on_total_amount > 0:
                export_items.append({
                    'name': 'Add-On',
                    'size': '-',
                    'price': float(add_on_total_amount),
                    'qty': 1,
                    'is_add_on': True
                })
            json.dump(export_items, tf)
        except Exception:
            # Fallback to original behavior
            json.dump(cart_items, tf)
        temp_path = tf.name
    script_path = os.path.join(os.path.dirname(__file__), "checkout.py")
    subprocess.Popen([sys.executable, script_path, temp_path])
    try:
        window.destroy()
    except Exception:
        pass

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=clear_cart,
    relief="flat"
)
button_9.place(
    x=788.911865234375,
    y=447.12646484375,
    width=90.61764526367188,
    height=39.73057174682617
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=checkout_cart,
    relief="flat"
)
button_10.place(
    x=893.470703125,
    y=447.12646484375,
    width=93.60504150390625,
    height=39.73057174682617
)

canvas.create_text(
    796.878173828125,
    372.86761474609375,
    anchor="nw",
    text="Add-On",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

_add_on_amount_text_id = canvas.create_text(
    936.0,
    371.0,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    353.0023193359375,
    anchor="nw",
    text="SubTotal",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

_subtotal_amount_text_id = canvas.create_text(
    936.2900390625,
    350.3536376953125,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

_total_amount_text_id = canvas.create_text(
    936.2900390625,
    414.5302734375,
    anchor="nw",
    text="₱0.00",
    fill="#1E1E1E",
    font=("Poppins SemiBold", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    412.59820556640625,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("Poppins SemiBold", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    297.0,
    28.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=202.0,
    y=16.0,
    width=190.0,
    height=22.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Mocha"),
    relief="flat"
)
button_11.place(
    x=367.0,
    y=131.0,
    width=78.0,
    height=133.0
)
button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Macchiato"),
    relief="flat"
)
button_12.place(
    x=463.0,
    y=131.0,
    width=78.0,
    height=133.0
)
button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Brusko"),
    relief="flat"
)
button_13.place(
    x=271.0,
    y=132.0,
    width=78.0,
    height=132.0
)
button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Vanilla"),
    relief="flat"
)
button_14.place(
    x=557.0,
    y=132.0,
    width=78.0,
    height=132.0
)
button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Caramel"),
    relief="flat"
)
button_15.place(
    x=653.0,
    y=132.0,
    width=78.0,
    height=132.0
)
button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Matcha"),
    relief="flat"
)
button_16.place(
    x=271.0,
    y=281.0,
    width=77.0,
    height=133.0
)
button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Fudge"),
    relief="flat"
)
button_17.place(
    x=366.0,
    y=281.0,
    width=78.0,
    height=133.0
)
button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_options_popup(window, on_add_item=add_item_to_cart, product_name="Spanish Latte"),
    relief="flat"
)
button_18.place(
    x=463.0,
    y=282.0,
    width=77.0,
    height=132.0
)

canvas.create_rectangle(
    734.0,
    132.0,
    746.0,
    196.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
