
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from pop_up import show_options_popup
import os
import sys
import subprocess


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\order history\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1035x534")
window.configure(bg = "#FFFFFF")

# Center the order window on the screen
try:
    window.update_idletasks()
    _w, _h = 1035, 534
    _sw = window.winfo_screenwidth()
    _sh = window.winfo_screenheight()
    _x = int((_sw - _w) / 2)
    _y = int((_sh - _h) / 2)
    window.geometry(f"{_w}x{_h}+{_x}+{_y}")
except Exception:
    pass


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 534,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    517.0,
    267.0,
    image=image_image_1
)

def open_coming_soon():
    try:
        script_path = os.path.join(os.path.dirname(__file__), "coming_soon.py")
        subprocess.Popen([sys.executable, script_path])
    finally:
        try:
            window.destroy()
        except Exception:
            pass


def open_options_popup():
    try:
        show_options_popup(window, on_add_item=add_item_to_cart)
    except Exception as e:
        print(f"Failed to open options popup: {e}")

# -------------------- Cart/Order list state + rendering --------------------
cart_items = []  # list of dicts: {name, size, price, qty}
cart_item_canvas_ids = []  # to clear and rerender item cards

subtotal_text_id = None
total_text_id = None

def add_item_to_cart(item):
    # If same name+size exists, increment qty; else append
    for existing in cart_items:
        if existing["name"] == item["name"] and existing["size"] == item["size"] and existing["price"] == item["price"]:
            existing["qty"] += item.get("qty", 1)
            break
    else:
        cart_items.append({
            "name": item["name"],
            "size": item.get("size", "Regular"),
            "price": float(item["price"]),
            "qty": int(item.get("qty", 1))
        })
    render_cart()

def change_item_qty(index, delta):
    if 0 <= index < len(cart_items):
        cart_items[index]["qty"] = max(0, cart_items[index]["qty"] + delta)
        if cart_items[index]["qty"] == 0:
            del cart_items[index]
        render_cart()

def render_cart():
    # Clear existing item drawings
    for _id in cart_item_canvas_ids:
        try:
            canvas.delete(_id)
        except Exception:
            pass
    cart_item_canvas_ids.clear()

    # Layout settings (right panel area ~ x 768-1005)
    left_x = 780
    right_x = 995
    y = 120
    card_height = 70
    v_gap = 14

    # Draw each item card
    for idx, it in enumerate(cart_items):
        # background card
        bg = canvas.create_rectangle(
            left_x, y, right_x, y + card_height, fill="#ECE3D1", outline="", width=0
        )
        cart_item_canvas_ids.append(bg)

        # Title: Name (Size)
        title = f"{it['name']}  ({it['size']})"
        t1 = canvas.create_text(
            left_x + 16, y + 12, anchor="nw", text=title, fill="#1E1E1E",
            font=("Poppins SemiBold", 12 * -1)
        )
        cart_item_canvas_ids.append(t1)

        # Price on right
        price_str = f"₱{it['price']:.2f}"
        tprice = canvas.create_text(
            right_x - 16, y + 12, anchor="ne", text=price_str, fill="#1E1E1E",
            font=("Poppins SemiBold", 12 * -1)
        )
        cart_item_canvas_ids.append(tprice)

        # Qty line like: "1  x  ₱29.00" in grey
        qty_line = f"{it['qty']}  x  ₱{it['price']:.2f}"
        t2 = canvas.create_text(
            left_x + 16, y + 36, anchor="nw", text=qty_line, fill="#9A9A9B",
            font=("Poppins Regular", 11 * -1)
        )
        cart_item_canvas_ids.append(t2)

        # Minus and plus simple circle buttons
        # Minus
        minus_circle = canvas.create_oval(
            right_x - 64, y + 36, right_x - 40, y + 60, outline="#9A9A9B", width=2
        )
        minus_line = canvas.create_line(
            right_x - 60, y + 48, right_x - 44, y + 48, fill="#9A9A9B", width=2
        )
        cart_item_canvas_ids.extend([minus_circle, minus_line])

        # Plus
        plus_circle = canvas.create_oval(
            right_x - 32, y + 36, right_x - 8, y + 60, outline="#9A9A9B", width=2
        )
        plus_h = canvas.create_line(
            right_x - 28, y + 48, right_x - 12, y + 48, fill="#9A9A9B", width=2
        )
        plus_v = canvas.create_line(
            right_x - 20, y + 40, right_x - 20, y + 56, fill="#9A9A9B", width=2
        )
        cart_item_canvas_ids.extend([plus_circle, plus_h, plus_v])

        # Bind clicks to adjust qty
        def bind_click(tag_id, cb):
            canvas.tag_bind(tag_id, "<Button-1>", lambda _e: cb())

        bind_click(minus_circle, lambda i=idx: change_item_qty(i, -1))
        bind_click(minus_line,   lambda i=idx: change_item_qty(i, -1))
        bind_click(plus_circle,  lambda i=idx: change_item_qty(i, +1))
        bind_click(plus_h,       lambda i=idx: change_item_qty(i, +1))
        bind_click(plus_v,       lambda i=idx: change_item_qty(i, +1))

        y += card_height + v_gap

    # Update totals
    subtotal = sum(it["price"] * it["qty"] for it in cart_items)
    total = subtotal  # add-on is fixed 0.00 for now
    if subtotal_text_id is not None:
        canvas.itemconfigure(subtotal_text_id, text=f"₱{subtotal:.2f}")
    if total_text_id is not None:
        canvas.itemconfigure(total_text_id, text=f"₱{total:.2f}")

canvas.create_rectangle(
    0.0,
    57.0,
    1035.0,
    535.0,
    fill="#EFE8D8",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1035.0,
    57.0,
    fill="#B96708",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=944.0,
    y=0.0,
    width=46.0,
    height=46.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    87.0,
    24.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    274.0,
    24.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=179.0,
    y=12.0,
    width=190.0,
    height=22.0
)

canvas.create_rectangle(
    34.0,
    75.0,
    236.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    135.0,
    288.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    501.0,
    287.0,
    image=image_image_4
)

canvas.create_text(
    58.0,
    81.0,
    anchor="nw",
    text="Menu",
    fill="#B96708",
    font=("Poppins ExtraBold", 32 * -1)
)

canvas.create_text(
    268.0,
    90.0,
    anchor="nw",
    text="Milk Tea",
    fill="#B96708",
    font=("Poppins Bold", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_2.place(
    x=51.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=49.0,
    y=189.0,
    width=171.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_4.place(
    x=49.0,
    y=136.0,
    width=171.0,
    height=36.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_5.place(
    x=51.0,
    y=290.0,
    width=171.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_6.place(
    x=51.0,
    y=338.0,
    width=171.0,
    height=36.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_7.place(
    x=51.0,
    y=387.0,
    width=171.0,
    height=35.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=open_coming_soon,
    relief="flat"
)
button_8.place(
    x=51.0,
    y=435.0,
    width=171.0,
    height=35.0
)

canvas.create_rectangle(
    768.0,
    75.0,
    1005.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    886.0,
    288.0,
    image=image_image_5
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=788.911865234375,
    y=447.12646484375,
    width=90.61764526367188,
    height=39.73057174682617
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=893.470703125,
    y=447.12646484375,
    width=93.60504150390625,
    height=39.73057174682617
)

# Add-On label remains same
canvas.create_text(
    796.878173828125,
    372.86761474609375,
    anchor="nw",
    text="Add-On",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    936.0,
    371.0,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    353.0023193359375,
    anchor="nw",
    text="SubTotal",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

subtotal_text_id = canvas.create_text(
    936.2900390625,
    350.3536376953125,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

total_text_id = canvas.create_text(
    936.2900390625,
    414.5302734375,
    anchor="nw",
    text="₱0.00",
    fill="#1E1E1E",
    font=("Poppins SemiBold", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    412.59820556640625,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("Poppins SemiBold", 12 * -1)
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_11.place(
    x=367.0,
    y=131.0,
    width=78.0,
    height=133.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_12.place(
    x=463.0,
    y=131.0,
    width=78.0,
    height=133.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_13.place(
    x=271.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_14.place(
    x=557.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_15.place(
    x=653.0,
    y=132.0,
    width=78.0,
    height=132.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_16.place(
    x=271.0,
    y=281.0,
    width=77.0,
    height=133.0
)

button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_17.place(
    x=366.0,
    y=281.0,
    width=78.0,
    height=133.0
)

button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_18.place(
    x=557.0,
    y=281.0,
    width=77.0,
    height=133.0
)

button_image_19 = PhotoImage(
    file=relative_to_assets("button_19.png"))
button_19 = Button(
    image=button_image_19,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_19.place(
    x=463.0,
    y=282.0,
    width=77.0,
    height=132.0
)

button_image_20 = PhotoImage(
    file=relative_to_assets("button_20.png"))
button_20 = Button(
    image=button_image_20,
    borderwidth=0,
    highlightthickness=0,
    command=open_options_popup,
    relief="flat"
)
button_20.place(
    x=652.0,
    y=282.0,
    width=78.0,
    height=132.0
)

canvas.create_rectangle(
    734.0,
    132.0,
    746.0,
    196.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
