
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import inspect
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Toplevel, Canvas, Entry, Text, Button, PhotoImage, Checkbutton, BooleanVar


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\order history\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def show_options_popup(parent, on_add_item=None, product_name=None):
    top = Toplevel(parent)
    top.title("Options")
    top.geometry("399x262")
    top.configure(bg = "#FFF8E7")

    # Center the popup relative to parent (fallback to screen center)
    try:
        top.update_idletasks()
        w, h = 399, 262
        # Prefer centering over the parent window if available
        try:
            px = parent.winfo_rootx()
            py = parent.winfo_rooty()
            pw = parent.winfo_width()
            ph = parent.winfo_height()
            x = int(px + (pw - w) / 2)
            y = int(py + (ph - h) / 2)
        except Exception:
            # Center on screen
            sw = top.winfo_screenwidth()
            sh = top.winfo_screenheight()
            x = int((sw - w) / 2)
            y = int((sh - h) / 2)
        top.geometry(f"{w}x{h}+{x}+{y}")
    except Exception:
        pass

    # Optional: keep the popup on top of the parent
    try:
        top.transient(parent)
        top.grab_set()
    except Exception:
        pass

    canvas = Canvas(
        top,
        bg = "#FFF8E7",
        height = 262,
        width = 399,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        37.0,
        28.0,
        anchor="nw",
        text="Options",
        fill="#000000",
        font=("Poppins Bold", 20 * -1)
    )

    canvas.create_text(
        37.0,
        61.0,
        anchor="nw",
        text="Size",
        fill="#000000",
        font=("Poppins SemiBold", 16 * -1)
    )

    # Track selected size; default Regular
    selected_size = {"value": "Regular"}

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        top,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: selected_size.update({"value": "Regular"}),
        relief="flat"
    )
    button_1.image = button_image_1  # prevent GC
    button_1.place(
        x=37.0,
        y=97.0,
        width=121.0,
        height=35.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        top,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: selected_size.update({"value": "Large"}),
        relief="flat"
    )
    button_2.image = button_image_2
    button_2.place(
        x=179.0,
        y=97.0,
        width=121.0,
        height=35.0
    )

    # Interactive checkbox for Add Extra Shot (only when called from menu_coffee.py)
    add_extra_var = BooleanVar(master=top, value=False)
    show_extra_option = False
    try:
        for frame_info in inspect.stack():
            filename = frame_info.filename or ""
            if filename.endswith("menu_coffee.py") or filename.endswith(os.sep + "menu_coffee.py"):
                show_extra_option = True
                break
    except Exception:
        pass
    checkbox = Checkbutton(
        top,
        variable=add_extra_var,
        onvalue=True,
        offvalue=False,
        bg="#FFF8E7",
        activebackground="#FFF8E7",
        highlightthickness=0,
        bd=0,
        takefocus=0
    )
    _extra_shot_added = {"done": False}

    def on_extra_toggle():
        # Only add once when checked, and only for menu_coffee
        if not show_extra_option:
            return
        try:
            if add_extra_var.get() and not _extra_shot_added["done"]:
                size = selected_size.get("value") or "Regular"
                item_name_local = product_name or "Coffee"
                if on_add_item:
                    on_add_item({
                        "name": f"{item_name_local} - Extra Shot",
                        "size": size,
                        "price": 5.00,
                        "qty": 1,
                        "is_add_on": True
                    })
                _extra_shot_added["done"] = True
        except Exception:
            pass

    if show_extra_option:
        checkbox.configure(command=on_extra_toggle)
        checkbox.place(x=40.0, y=146.0)
        text_id_1 = canvas.create_text(
            68.0,
            146.0,
            anchor="nw",
            text="Add Extra Shot",
            fill="#1E1E1E",
            font=("Inter", 16 * -1)
        )
        text_id_2 = canvas.create_text(
            68.0,
            168.0,
            anchor="nw",
            text="(+₱5.00)",
            fill="#757575",
            font=("Inter", 16 * -1)
        )
        canvas.tag_bind(text_id_1, "<Button-1>", lambda _e: (add_extra_var.set(not add_extra_var.get()), on_extra_toggle()))
        canvas.tag_bind(text_id_2, "<Button-1>", lambda _e: (add_extra_var.set(not add_extra_var.get()), on_extra_toggle()))
    else:
        try:
            checkbox.place_forget()
        except Exception:
            pass

    button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
    def on_add():
        try:
            size = selected_size.get("value") or "Regular"
            price = 39.00 if size == "Large" else 29.00
            # Price stays base; extra shot is a separate add-on line for Coffee
            item_name = product_name or "Chocolate"
            # If extra shot is selected, reflect in item name visually (no price change)
            try:
                if add_extra_var.get():
                    item_name = f"{item_name} w ES"
            except Exception:
                pass
            if on_add_item:
                on_add_item({
                    "name": item_name,
                    "size": size,
                    "price": price,
                    "qty": 1
                })
        finally:
            top.destroy()

    def on_cancel():
        try:
            top.destroy()
        except Exception:
            pass

    button_3 = Button(
        top,
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=on_cancel,
        relief="flat"
    )
    button_3.image = button_image_3
    button_3.place(
        x=193.0,
        y=205.0,
        width=90.61764526367188,
        height=39.73057174682617
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        top,
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=on_add,
        relief="flat"
    )
    button_4.image = button_image_4
    button_4.place(
        x=292.0,
        y=205.0,
        width=93.60504150390625,
        height=39.73057174682617
    )

    top.resizable(False, False)
    return top
