
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Toplevel, Canvas, Entry, Text, Button, PhotoImage, Checkbutton, BooleanVar


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\order history\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def show_options_popup(parent, on_add_item=None):
    top = Toplevel(parent)
    top.title("Options")
    top.geometry("399x262")
    top.configure(bg = "#FFF8E7")

    # Optional: keep the popup on top of the parent
    try:
        top.transient(parent)
        top.grab_set()
    except Exception:
        pass

    canvas = Canvas(
        top,
        bg = "#FFF8E7",
        height = 262,
        width = 399,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        37.0,
        28.0,
        anchor="nw",
        text="Options",
        fill="#000000",
        font=("Poppins Bold", 20 * -1)
    )

    canvas.create_text(
        37.0,
        61.0,
        anchor="nw",
        text="Size",
        fill="#000000",
        font=("Poppins SemiBold", 16 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        top,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (on_add_item and on_add_item({
            "name": "Chocolate",
            "size": "Regular",
            "price": 29.00,
            "qty": 1
        }), top.destroy()),
        relief="flat"
    )
    button_1.image = button_image_1  # prevent GC
    button_1.place(
        x=37.0,
        y=97.0,
        width=121.0,
        height=35.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        top,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.image = button_image_2
    button_2.place(
        x=179.0,
        y=97.0,
        width=121.0,
        height=35.0
    )

    # Interactive checkbox for Add Extra Shot
    add_extra_var = BooleanVar(master=top, value=False)
    checkbox = Checkbutton(
        top,
        variable=add_extra_var,
        onvalue=True,
        offvalue=False,
        bg="#FFF8E7",
        activebackground="#FFF8E7",
        highlightthickness=0,
        bd=0,
        takefocus=0
    )
    checkbox.place(x=40.0, y=146.0)

    def toggle_add_extra():
        try:
            add_extra_var.set(not add_extra_var.get())
        except Exception:
            pass

    text_id_1 = canvas.create_text(
        68.0,
        146.0,
        anchor="nw",
        text="Add Extra Shot",
        fill="#1E1E1E",
        font=("Inter", 16 * -1)
    )

    text_id_2 = canvas.create_text(
        68.0,
        168.0,
        anchor="nw",
        text="(+₱5.00)",
        fill="#757575",
        font=("Inter", 16 * -1)
    )

    # Make the label texts clickable to toggle the checkbox
    canvas.tag_bind(text_id_1, "<Button-1>", lambda _e: toggle_add_extra())
    canvas.tag_bind(text_id_2, "<Button-1>", lambda _e: toggle_add_extra())

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        top,
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.image = button_image_3
    button_3.place(
        x=193.0,
        y=205.0,
        width=90.61764526367188,
        height=39.73057174682617
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        top,
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=top.destroy,
        relief="flat"
    )
    button_4.image = button_image_4
    button_4.place(
        x=292.0,
        y=205.0,
        width=93.60504150390625,
        height=39.73057174682617
    )

    top.resizable(False, False)
    return top
