# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox
from utils import UtilityFunctions
import mysql.connector
import sys
import os

OUTPUT_PATH = Path(__file__).parent

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def relative_to_assets(path: str) -> Path:
    """Get path to assets in the resetpass resources folder"""
    possible_paths = [
        resource_path(f"resources/resetpass/{path}"),
        resource_path(f"resetpass/resources/{path}"),
        os.path.join(OUTPUT_PATH, "resources", "resetpass", path),
        os.path.join(OUTPUT_PATH, "resetpass", "resources", path),
        resource_path(path),
    ]
    
    for asset_path in possible_paths:
        if os.path.exists(asset_path):
            return Path(asset_path)
    
    # If no path found, return the most likely one
    return Path(possible_paths[0])

class PasswordResetWindow:
    def __init__(self, parent, user_email, show_login_callback, get_db_connection):
        self.parent = parent
        self.user_email = user_email
        self.show_login_callback = show_login_callback
        self.get_db_connection = get_db_connection
        self.images = []  # Keep references to images
        
        # Load eye images for toggle
        self.button_hidden_img = self.load_image("button_eye.png")
        self.button_view_img = self.load_image("button_eye.png")
        
        self.setup_ui()
        
    def load_image(self, path: str):
        """Load image and keep reference to prevent garbage collection"""
        try:
            image_path = relative_to_assets(path)
            if not image_path.exists():
                print(f"Image not found: {image_path}")
                return None
            photo_image = PhotoImage(file=image_path)
            self.images.append(photo_image)
            return photo_image
        except Exception as e:
            print(f"Error loading image {path}: {e}")
            return None
        
    def setup_ui(self):
        """Setup the password reset UI"""
        # Clear any existing widgets first
        for widget in self.parent.winfo_children():
            widget.destroy()
        
        # Create canvas
        self.canvas = Canvas(
            self.parent,
            bg="#FFFFFF",
            height=440,
            width=800,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)
        
        # Load background image
        image_image_1 = self.load_image("image_1.png")
        if image_image_1:
            self.canvas.create_image(400.0, 220.0, image=image_image_1)

        # Background rectangle
        self.canvas.create_rectangle(
    49.0,
    87.0,
    316.0,
    276.0,
    fill="#3A280F",
            outline=""
        )

        # Reset password button
        button_image_1 = self.load_image("button_resetpass.png")
        if button_image_1:
            self.button_resetpass = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
                command=self.reset_password,
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_resetpass = Button(
                text="Reset Password",
                borderwidth=0,
                highlightthickness=0,
                command=self.reset_password,
                relief="flat",
                bg="#D2691E",
                fg="#FFFFFF",
                cursor="hand2"
            )
        self.button_resetpass.place(x=54.0, y=323.0, width=245.0, height=42.0)

        # New password entry
        entry_image_1 = self.load_image("entry_newpass.png")
        if entry_image_1:
            self.canvas.create_image(177.5, 174.0, image=entry_image_1)
            
        self.entry_newpass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
            highlightthickness=0,
            show="●",
            font=("Inter", 12)
        )
        self.entry_newpass.place(x=63.0, y=154.0, width=229.0, height=38.0)
        self.entry_newpass.bind('<Return>', lambda e: self.entry_confirmpass.focus())

        # New password toggle button
        if self.button_hidden_img:
            self.button_toggle_new = Button(
                image=self.button_hidden_img,
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_newpass, self.button_toggle_new),
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_toggle_new = Button(
                text="👁",
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_newpass, self.button_toggle_new),
                relief="flat",
                cursor="hand2"
            )
        self.button_toggle_new.place(x=272.0, y=164.0, width=20.0, height=19.0)

        # Confirm password entry
        entry_image_2 = self.load_image("entry_confirmpass.png")
        if entry_image_2:
            self.canvas.create_image(178.5, 225.0, image=entry_image_2)
            
        self.entry_confirmpass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
            highlightthickness=0,
            show="●",
            font=("Inter", 12)
        )
        self.entry_confirmpass.place(x=64.0, y=205.0, width=229.0, height=38.0)
        self.entry_confirmpass.bind('<Return>', lambda e: self.reset_password())

        # Confirm password toggle button
        if self.button_view_img:
            self.button_toggle_confirm = Button(
                image=self.button_view_img,
    borderwidth=0,
    highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_confirmpass, self.button_toggle_confirm),
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_toggle_confirm = Button(
                text="👁",
    borderwidth=0,
    highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_confirmpass, self.button_toggle_confirm),
                relief="flat",
                cursor="hand2"
            )
        self.button_toggle_confirm.place(x=272.0, y=217.0, width=20.0, height=19.0)

        # Title text
        self.canvas.create_text(
    38.0,
    87.0,
    anchor="nw",
    text="Reset Password",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

        # Set focus to new password entry
        self.entry_newpass.focus()

    def toggle_password_visibility(self, entry_widget, button_widget):
        """Toggle the visibility of the password field"""
        if entry_widget.cget('show') == "●":
            entry_widget.config(show="")
            if self.button_hidden_img:
                button_widget.config(image=self.button_hidden_img)
        else:
            entry_widget.config(show="●")
            if self.button_view_img:
                button_widget.config(image=self.button_view_img)

    def reset_password(self):
        """Reset the user's password"""
        new_password = self.entry_newpass.get().strip()
        confirm_password = self.entry_confirmpass.get().strip()

        if not new_password or not confirm_password:
            messagebox.showerror("Error", "Please fill in both password fields")
            return

        if new_password != confirm_password:
            messagebox.showerror("Error", "Passwords do not match")
            return

        if len(new_password) < 6:
            messagebox.showerror("Error", "Password must be at least 6 characters long")
            return

        db_connection = self.get_db_connection()
        if not db_connection:
            messagebox.showerror("Database Error", "Cannot connect to database")
            return

        try:
            cursor = db_connection.cursor()
            hashed_password = UtilityFunctions.hash_password(new_password)
            cursor.execute(
                "UPDATE users SET password_hash = %s WHERE email = %s",
                (hashed_password, self.user_email)
            )
            if cursor.rowcount == 0:
                messagebox.showerror("Error", "Failed to reset password. User not found.")
                return
            db_connection.commit()
            messagebox.showinfo("Success", "Password reset successfully!")
            self.show_login_callback()
        except Exception as e:
            messagebox.showerror("Error", f"Failed to reset password: {str(e)}")
            db_connection.rollback()
        finally:
            if db_connection and db_connection.is_connected():
                cursor.close()

    def destroy(self):
        """Clean up the window"""
        for widget in self.parent.winfo_children():
            widget.destroy()

