
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\output tk\bnyes\1\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x440")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 440,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    400.0,
    220.0,
    image=image_image_1
)

canvas.create_rectangle(
    49.0,
    87.0,
    316.0,
    276.0,
    fill="#3A280F",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_resetpass.png"))
button_resetpass = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_resetpass clicked"),
    relief="flat"
)
button_resetpass.place(
    x=54.0,
    y=323.0,
    width=245.0,
    height=42.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_newpass.png"))
entry_bg_1 = canvas.create_image(
    177.5,
    174.0,
    image=entry_image_1
)
entry_newpass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_newpass.place(
    x=63.0,
    y=154.0,
    width=229.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_confirmpass.png"))
entry_bg_2 = canvas.create_image(
    178.5,
    225.0,
    image=entry_image_2
)
entry_confirmpass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_confirmpass.place(
    x=64.0,
    y=205.0,
    width=229.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_eye.png"))
button_eye = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_eye clicked"),
    relief="flat"
)
button_eye.place(
    x=272.0,
    y=164.0,
    width=20.0,
    height=19.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_eye.png"))
button_eye = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_eye clicked"),
    relief="flat"
)
button_eye.place(
    x=272.0,
    y=217.0,
    width=20.0,
    height=19.0
)

canvas.create_text(
    38.0,
    87.0,
    anchor="nw",
    text="Reset Password",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)
window.resizable(False, False)
window.mainloop()
