
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox, simpledialog
import os
import sys
import subprocess
import smtplib
import ssl
import random
import string
import time
from email.message import EmailMessage
import bcrypt
from db_config import db
from dotenv import load_dotenv

# Load environment variables
load_dotenv()



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Downloads\Output_design\signup\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def generate_otp(length: int = 6) -> str:
    """Generate a numeric OTP code of given length."""
    digits = string.digits
    return ''.join(random.choice(digits) for _ in range(length))


def send_otp_email(recipient_email: str, otp_code: str) -> bool:
    """Send OTP to recipient using SMTP settings from environment variables."""

    smtp_host = os.getenv('SMTP_HOST')
    smtp_port = int(os.getenv('SMTP_PORT') or 587)
    smtp_user = os.getenv('SMTP_USER')
    smtp_pass = os.getenv('SMTP_PASS')
    smtp_from = os.getenv('SMTP_FROM') or smtp_user
    use_tls = (os.getenv('SMTP_USE_TLS', 'true').lower() != 'false')

    if not all([smtp_host, smtp_port, smtp_user, smtp_pass, smtp_from]):
        messagebox.showerror(
            "Email Not Configured",
            "SMTP settings are missing. Please set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS (and optional SMTP_FROM)."
        )
        return False

    # ✅ Create HTML email
    subject = "Your BigBrew Verification Code"
    html_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif; background-color: #f6f6f6; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background-color: white; border-radius: 10px; padding: 20px; box-shadow: 0 2px 6px rgba(0,0,0,0.1);">
                <h2 style="color: #3A280F; text-align: center;">BigBrew Account Verification</h2>
                <p>Hello,</p>
                <p>Your verification code is:</p>
                <div style="text-align: center; margin: 30px 0;">
                    <span style="display: inline-block; background-color: #3A280F; color: white; font-size: 24px; font-weight: bold; padding: 10px 20px; border-radius: 8px;">
                        {otp_code}
                    </span>
                </div>
                <p>This code will expire in 10 minutes.</p>
                <p>If you did not request this, you can ignore this email.</p>
                <p style="color: #999; font-size: 12px; text-align: center;">© 2025 BigBrew. All rights reserved.</p>
            </div>
        </body>
    </html>
    """

    # ✅ Build email message
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = smtp_from
    message["To"] = recipient_email
    message.set_content("Your verification code is: " + otp_code)  # fallback plain text
    message.add_alternative(html_body, subtype="html")

    # ✅ Send the message
    try:
        if use_tls:
            context = ssl.create_default_context()
            with smtplib.SMTP(smtp_host, smtp_port, timeout=20) as server:
                server.starttls(context=context)
                server.login(smtp_user, smtp_pass)
                server.send_message(message)
        else:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=20) as server:
                server.login(smtp_user, smtp_pass)
                server.send_message(message)
        return True
    except Exception as e:
        messagebox.showerror("Email Error", f"Failed to send verification email: {str(e)}")
        return False



def create_users_table_if_needed() -> None:
    """Create the users table if it doesn't exist."""
    create_sql = (
        """
        CREATE TABLE IF NOT EXISTS users (
            user_id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(50) UNIQUE NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            user_type ENUM('admin', 'manager', 'cashier', 'barista', 'inventory_manager') DEFAULT 'cashier',
            first_name VARCHAR(50) NOT NULL,
            last_name VARCHAR(50) NOT NULL,
            contact_number VARCHAR(20),
            address TEXT,
            hire_date DATE,
            salary DECIMAL(10,2),
            is_active BOOLEAN DEFAULT TRUE,
            last_login TIMESTAMP NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
        """
    )
    try:
        db.execute_query(create_sql)
    except Exception:
        # Non-fatal; will error during insert anyway if table truly missing
        pass


def ensure_unique_username(base_username: str) -> str:
    """Ensure unique username by appending digits if necessary."""
    candidate = base_username[:50]
    suffix = 1
    while True:
        existing = db.execute_query(
            "SELECT user_id FROM users WHERE username = %s",
            (candidate,),
            fetch=True
        )
        if not existing:
            return candidate
        suffix += 1
        tail = f"{suffix}"
        # keep total length within 50
        candidate = (base_username[: max(1, 50 - len(tail))] + tail)


def insert_user(username: str, email: str, password_hash: str) -> bool:
    """Insert a new user record with minimal required fields."""
    insert_sql = (
        "INSERT INTO users (username, email, password_hash, first_name, last_name) "
        "VALUES (%s, %s, %s, %s, %s)"
    )
    result = db.execute_query(insert_sql, (username, email, password_hash, '', ''))
    return bool(result)


def handle_signup():
    email = entry_email.get().strip()
    password = entry_pass.get()
    confirm = entry_confirmpass.get()

    if not email or '@' not in email:
        messagebox.showerror("Invalid Email", "Please enter a valid email address.")
        return
    if not password or len(password) < 8:
        messagebox.showerror("Weak Password", "Password must be at least 8 characters long.")
        return
    if password != confirm:
        messagebox.showerror("Mismatch", "Password and Confirm Password do not match.")
        return

    if not db.test_connection():
        messagebox.showerror("Database Error", "Unable to connect to database. Please try again later.")
        return

    create_users_table_if_needed()

    otp = generate_otp()
    if not send_otp_email(email, otp):
        return

    # Ask user to enter OTP (up to 3 attempts)
    max_attempts = 3
    for attempt in range(max_attempts):
        entered = simpledialog.askstring(
            "Email Verification",
            "Enter the 6-digit verification code sent to your email:",
            parent=window,
            show='*'
        )
        if entered is None:
            # user cancelled
            return
        if entered.strip() == otp:
            break
        else:
            if attempt < max_attempts - 1:
                messagebox.showerror("Invalid Code", "Incorrect code. Please try again.")
            else:
                messagebox.showerror("Verification Failed", "Too many incorrect attempts.")
                return

    # Hash and insert
    try:
        password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    except Exception as e:
        messagebox.showerror("Error", f"Failed to hash password: {str(e)}")
        return

    base_username = email.split('@', 1)[0]
    username = ensure_unique_username(base_username)

    if insert_user(username, email, password_hash):
        messagebox.showinfo("Success", "Your account has been created. You can now log in.")
        # Clear fields
        entry_email.delete(0, 'end')
        entry_pass.delete(0, 'end')
        entry_confirmpass.delete(0, 'end')
    else:
        messagebox.showerror("Error", "Failed to create account. Email may already be registered.")


window = Tk()

window.geometry("800x440")
window.configure(bg = "#FFFFFF")
try:
    window.update_idletasks()
    width, height = 800, 440
    screen_width = window.winfo_screenwidth()
    screen_height = window.winfo_screenheight()
    x = (screen_width - width) // 2
    y = (screen_height - height) // 2
    window.geometry(f"{width}x{height}+{x}+{y}")
except Exception:
    pass


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 440,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    400.0,
    220.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_pass.png"))
entry_bg_1 = canvas.create_image(
    177.5,
    240.0,
    image=entry_image_1
)
entry_pass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0,
    show='*'
)
entry_pass.place(
    x=63.0,
    y=220.0,
    width=229.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_email.png"))
entry_bg_2 = canvas.create_image(
    176.5,
    188.0,
    image=entry_image_2
)
entry_email = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_email.place(
    x=62.0,
    y=168.0,
    width=229.0,
    height=38.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_confirmpass.png"))
entry_bg_3 = canvas.create_image(
    178.5,
    291.0,
    image=entry_image_3
)
entry_confirmpass = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0,
    show='*'
)
entry_confirmpass.place(
    x=64.0,
    y=271.0,
    width=229.0,
    height=38.0
)

def toggle_entry_password(target_entry):
    current = target_entry.cget('show')
    target_entry.config(show='' if current == '*' else '*')

button_image_eye_pass = PhotoImage(
    file=relative_to_assets("button_eye.png"))
button_eye_pass = Button(
    image=button_image_eye_pass,
    borderwidth=0,
    highlightthickness=0,
    command=lambda e=entry_pass: toggle_entry_password(e),
    relief="flat"
)
button_eye_pass.place(
    x=272.0,
    y=230.0,
    width=20.0,
    height=19.0
)

button_image_eye_confirm = PhotoImage(
    file=relative_to_assets("button_eye.png"))
button_eye_confirm = Button(
    image=button_image_eye_confirm,
    borderwidth=0,
    highlightthickness=0,
    command=lambda e=entry_confirmpass: toggle_entry_password(e),
    relief="flat"
)
button_eye_confirm.place(
    x=272.0,
    y=283.0,
    width=20.0,
    height=19.0
)

canvas.create_rectangle(
    110.0,
    124.0,
    247.0,
    140.0,
    fill="#3A280F",
    outline="")

button_image_3 = PhotoImage(
    file=relative_to_assets("button_login.png"))
button_login = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_login(),
    relief="flat"
)
button_login.place(
    x=70.0,
    y=376.0,
    width=204.0,
    height=26.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_signup.png"))
button_signup = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=handle_signup,
    relief="flat"
)
button_signup.place(
    x=54.0,
    y=323.0,
    width=245.0,
    height=42.0
)
def open_login():
    try:
        window.destroy()
    except Exception:
        pass
    try:
        script_path = Path(__file__).parent / "login.py"
        subprocess.Popen([sys.executable, str(script_path)])
    except Exception as e:
        messagebox.showerror("Error", f"Unable to open Login: {str(e)}")
window.resizable(False, False)
window.mainloop()
