
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from datetime import datetime
import shutil

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Toplevel, Canvas, Entry, Text, Button, Radiobutton, StringVar, Frame, Scrollbar, filedialog, messagebox
import sys
import json


OUTPUT_PATH = Path(__file__).resolve().parent
PROJECT_ROOT = OUTPUT_PATH.parent.parent
ASSETS_PATH = PROJECT_ROOT / "resources" / "checkout"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def run_checkout(cart_items, parent=None, add_on_total=0.0, customer_id=None, require_proof_methods=None):
    is_modal = parent is not None
    window = Toplevel(parent) if is_modal else Tk()
    window.geometry("399x528")
    window.configure(bg="#FFF8E7")
    # Center window on screen
    try:
        window.update_idletasks()
        w, h = 399, 528
        sw = window.winfo_screenwidth()
        sh = window.winfo_screenheight()
        x = int((sw - w) / 2)
        y = int((sh - h) / 2)
        window.geometry(f"{w}x{h}+{x}+{y}")
    except Exception:
        pass
    if is_modal:
        try:
            window.transient(parent)
            window.grab_set()
        except Exception:
            pass

    canvas = Canvas(
        window,
        bg="#FFF8E7",
        height=528,
        width=399,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    canvas.create_text(
        37.0, 28.0, anchor="nw", text="Checkout", fill="#000000", font=("Poppins Bold", 20 * -1)
    )
    # Order summary text
    order_lines = []
    subtotal = 0.0
    add_on_total_value = float(add_on_total or 0.0)
    try:
        customer_id_value = int(customer_id) if customer_id is not None else None
    except (TypeError, ValueError):
        customer_id_value = None
    
    # Handle both string and dictionary items
    def process_item(item):
        if isinstance(item, str):
            try:
                # Try to parse JSON string if needed
                import json
                item = json.loads(item)
            except:
                # Fallback for plain string
                return {"qty": 1, "name": item, "size": "Regular", "price": 0}
        return item if isinstance(item, dict) else {"qty": 1, "name": str(item), "size": "Regular", "price": 0}

    # Process each item
    for item in cart_items:
        item_dict = process_item(item)
        qty = int(item_dict.get("qty", 1))
        name = str(item_dict.get("name", "?"))
        size = str(item_dict.get("size", "Regular"))
        try:
            price = float(item_dict.get("price", 0))
        except (ValueError, TypeError):
            price = 0.0
            
        order_lines.append(f"- {name} ({size}) x {qty} ₱{price * qty:,.2f}")
        subtotal += price * qty
    # Text for scrollable list (order lines only)
    summary_list = "\n".join(order_lines)

    # Scrollable order list panel to prevent overlap with payment options
    list_container = Frame(window, bg="#FFF8E7")
    list_container.place(x=37, y=75, width=325, height=170)

    list_scrollbar = Scrollbar(list_container, orient="vertical")
    list_scrollbar.pack(side="right", fill="y")

    summary_text = Text(
        list_container,
        wrap="word",
        bd=0,
        highlightthickness=0,
        font=("Inter", 16 * -1),
        bg="#FFF8E7",
        yscrollcommand=list_scrollbar.set,
    )
    summary_text.pack(side="left", fill="both", expand=True)
    list_scrollbar.config(command=summary_text.yview)
    summary_text.insert("1.0", summary_list)
    summary_text.config(state="disabled")
    # Static (non-scrollable) totals and Payment label
    subtotal_y = 75 + 170 + 15
    canvas.create_text(
        37.0, subtotal_y, anchor="nw",
        text=f"Subtotal: ₱{subtotal:,.2f}",
        fill="#1E1E1E", font=("Inter", 16 * -1)
    )

    current_y = subtotal_y + 20.0
    if add_on_total_value > 0:
        canvas.create_text(
            37.0, current_y, anchor="nw",
            text=f"Add-ons: ₱{add_on_total_value:,.2f}",
            fill="#1E1E1E", font=("Inter", 16 * -1)
        )
        current_y += 20.0

    grand_total = subtotal + add_on_total_value
    canvas.create_text(
        37.0, current_y, anchor="nw",
        text=f"Total: ₱{grand_total:,.2f}",
        fill="#1E1E1E", font=("Inter", 16 * -1)
    )
    current_y += 28.0
    canvas.create_text(
        37.0, current_y, anchor="nw",
        text="Payment:",
        fill="#1E1E1E", font=("Inter", 16 * -1)
    )
    # Payment method (radio buttons) - exclusive (cannot unselect all)
    pay_method = StringVar(value="Cash")
    y_base = current_y + 27.0
    methods = ["Cash", "GCash", "Maya"]
    for idx, txt in enumerate(methods):
        rb = Radiobutton(
            window, text=txt, variable=pay_method, value=txt,
            anchor="w", font=("Inter", 16 * -1), bg="#FFF8E7"
        )
        rb.place(x=37, y=y_base + 31*idx)
    def close_window():
        try:
            if is_modal:
                window.grab_release()
        except Exception:
            pass
        window.destroy()

    def prompt_proof_upload(amount: float, payment_label: str):
        proof_window = Toplevel(window)
        proof_window.title("Upload Proof of Payment")
        proof_window.geometry("420x220")
        proof_window.configure(bg="#FFF8E7")

        try:
            proof_window.transient(window)
            proof_window.grab_set()
        except Exception:
            pass

        try:
            proof_window.update_idletasks()
            w, h = 420, 220
            try:
                px = window.winfo_rootx()
                py = window.winfo_rooty()
                pw = window.winfo_width()
                ph = window.winfo_height()
                x = int(px + (pw - w) / 2)
                y = int(py + (ph - h) / 2)
            except Exception:
                sw = proof_window.winfo_screenwidth()
                sh = proof_window.winfo_screenheight()
                x = int((sw - w) / 2)
                y = int((sh - h) / 2)
            proof_window.geometry(f"{w}x{h}+{x}+{y}")
        except Exception:
            pass

        proof_canvas = Canvas(
            proof_window,
            bg="#FFF8E7",
            height=220,
            width=420,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )
        proof_canvas.place(x=0, y=0)

        proof_canvas.create_text(
            30,
            20,
            anchor="nw",
            text="Proof of Payment",
            fill="#000000",
            font=("Poppins Bold", 18 * -1),
        )
        proof_canvas.create_text(
            30,
            60,
            anchor="nw",
            text=f"Payment Method: {payment_label}\nAmount: ₱{amount:,.2f}",
            fill="#1E1E1E",
            font=("Poppins Regular", 12 * -1),
        )

        proof_path_var = StringVar()

        def browse_proof():
            selected = filedialog.askopenfilename(
                title="Select Proof of Payment",
                filetypes=[
                    ("Image files", "*.png *.jpg *.jpeg *.gif *.bmp"),
                    ("PDF files", "*.pdf"),
                    ("All files", "*.*"),
                ],
            )
            if selected:
                proof_path_var.set(selected)

        entry_frame = Frame(proof_window, bg="#FFF8E7")
        entry_frame.place(x=30, y=110, width=360, height=30)
        entry = Entry(entry_frame, textvariable=proof_path_var, bd=1, relief="solid")
        entry.pack(side="left", fill="both", expand=True)
        browse_btn = Button(
            entry_frame,
            text="Browse",
            command=browse_proof,
            bg="#6C757D",
            fg="white",
            relief="flat",
        )
        browse_btn.pack(side="right")

        result = {"path": None}

        def submit_proof():
            path = proof_path_var.get().strip()
            if not path:
                messagebox.showinfo("Proof Required", "Please select a file before submitting.")
                return
            result["path"] = path
            proof_window.destroy()

        def cancel_proof():
            result["path"] = None
            proof_window.destroy()

        button_bar = Frame(proof_window, bg="#FFF8E7")
        button_bar.place(relx=0.5, y=170, anchor="center")

        cancel_btn = Button(
            button_bar,
            text="Cancel",
            bg="#DC3545",
            fg="white",
            relief="flat",
            command=cancel_proof,
            width=12,
        )
        cancel_btn.pack(side="left", padx=10)

        submit_btn = Button(
            button_bar,
            text="Submit",
            bg="#28A745",
            fg="white",
            relief="flat",
            command=submit_proof,
            width=12,
        )
        submit_btn.pack(side="left", padx=10)

        proof_window.resizable(False, False)
        window.wait_window(proof_window)
        return result["path"]

    def confirm_action():
        import tkinter.messagebox as mbox
        if not pay_method.get():
            mbox.showinfo("Select Payment", "Please select a payment method.")
            return

        requires_proof = False
        if require_proof_methods:
            try:
                normalized = {m.strip().lower() for m in require_proof_methods}
                requires_proof = pay_method.get().strip().lower() in normalized
            except Exception:
                requires_proof = False
        else:
            requires_proof = pay_method.get().lower().startswith(("gcash", "card", "maya"))

        proof_source = None
        proof_blob_data = None
        if requires_proof:
            proof_source = prompt_proof_upload(grand_total, pay_method.get())
            if not proof_source:
                mbox.showinfo("Proof Required", "Checkout cancelled. No proof of payment uploaded.")
                return
        else:
            proceed = mbox.askyesno(
                "Confirm Payment",
                f"You selected Cash payment.\n\nConfirm checkout for ₱{grand_total:,.2f}?",
            )
            if not proceed:
                return

        try:
            from app.services.shared_state import save_purchase_to_db, clear_cart

            total = grand_total

            payment_method_value = pay_method.get().lower().split()[0]
            proof_relative_path = None

            if proof_source:
                proof_storage_dir = PROJECT_ROOT / "payment_proofs"
                proof_storage_dir.mkdir(parents=True, exist_ok=True)
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                source_path = Path(proof_source)
                proof_destination = proof_storage_dir / f"{timestamp}_{source_path.name}"
                try:
                    with open(proof_source, "rb") as blob_file:
                        proof_blob_data = blob_file.read()
                except Exception as blob_exc:
                    mbox.showerror("Upload Error", f"Failed to read proof of payment:\n{blob_exc}")
                    return

                try:
                    shutil.copy2(source_path, proof_destination)
                except Exception as copy_error:
                    mbox.showerror("Upload Error", f"Failed to copy proof of payment:\n{copy_error}")
                    return
                proof_relative_path = str(proof_destination.relative_to(PROJECT_ROOT))

            sale_id = save_purchase_to_db(
                customer_id=customer_id_value,
                total_amount=total,
                payment_method=payment_method_value,
                items=cart_items,
                proof_of_payment_path=proof_relative_path,
                proof_of_payment_blob=proof_blob_data,
            )

            if sale_id:
                mbox.showinfo(
                    "Checkout",
                    f"Order #{sale_id} confirmed!\nPayment: {pay_method.get()}\nTotal: ₱{total:,.2f}"
                    + (f"\nProof saved to:\n{proof_destination}" if proof_source else ""),
                )
                clear_cart()
                close_window()
                if not is_modal:
                    try:
                        import subprocess, os, sys

                        home_script = os.path.join(OUTPUT_PATH, "home.py")
                        if os.path.exists(home_script):
                            subprocess.Popen([sys.executable, home_script], cwd=str(OUTPUT_PATH))
                    except Exception:
                        pass
            else:
                mbox.showerror("Error", "Failed to save order. Please try again.")
        except Exception as e:
            mbox.showerror("Error", f"Checkout failed: {str(e)}")
            print(f"Checkout error: {e}")

    buttons_y = y_base + 31 * len(methods) + 30
    button_cancel = Button(
        window,
        text="Cancel",
        font=("Poppins", 12, "bold"),
        bg="#DC3545",
        fg="white",
        activebackground="#c82333",
        activeforeground="white",
        relief="flat",
        command=close_window,
        width=12,
        height=1,
    )
    button_cancel.place(x=160, y=buttons_y)

    button_confirm = Button(
        window,
        text="Checkout",
        font=("Poppins", 12, "bold"),
        bg="#28A745",
        fg="white",
        activebackground="#218838",
        activeforeground="white",
        relief="flat",
        command=confirm_action,
        width=12,
        height=1,
    )
    button_width = 120
    button_spacing = 20
    total_width = button_width * 2 + button_spacing
    start_x = (window.winfo_width() - total_width) // 2

    button_cancel.place(x=start_x, y=buttons_y, width=button_width)
    button_confirm.place(x=start_x + button_width + button_spacing, y=buttons_y, width=button_width)
    window.resizable(False, False)
    if is_modal and parent is not None:
        parent.wait_window(window)
    else:
        window.mainloop()
# Only run if executed as script for testing demo
if __name__ == "__main__":
    cart = None
    if len(sys.argv) > 1:
        try:
            # Read cart from temp file passed as command line argument
            with open(sys.argv[1], 'r') as f:
                cart = json.load(f)
        except Exception as ex:
            print("Failed to read order cart for checkout:", ex)
            cart = None
    if cart is None:
        cart = [{'name': 'Chocolate', 'size': 'Regular', 'price': 29.00, 'qty': 1}]
    if isinstance(cart, dict):
        cart_items_data = cart.get("items", [])
        add_on_total_cli = cart.get("add_on_total", 0.0)
        customer_id_cli = cart.get("customer_id")
    else:
        cart_items_data = cart
        add_on_total_cli = 0.0
        customer_id_cli = None
    run_checkout(cart_items_data, add_on_total=add_on_total_cli, customer_id=customer_id_cli)
