
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import base64

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label, Listbox, Frame, Scrollbar, Toplevel
from tkinter import ttk
from tkinter import messagebox
from app.ui.pop_up import show_options_popup
import os
import sys
import subprocess
from app.repositories.product_repository import ProductRepository
from app.services.shared_state import (
    add_item,
    change_item_qty,
    get_state,
    clear_cart as shared_clear_cart,
    export_for_checkout,
    add_item_from_db,
    set_current_customer,
)
from app.ui.checkout import run_checkout


OUTPUT_PATH = Path(__file__).resolve().parent
PROJECT_ROOT = OUTPUT_PATH.parent.parent
ASSETS_PATH = Path(__file__).resolve().parents[2] / "resources" / "order"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


customer_id_arg = None
for arg in sys.argv[1:]:
    if arg.startswith("--customer-id="):
        value = arg.split("=", 1)[1]
        if value:
            try:
                customer_id_arg = int(value)
            except ValueError:
                customer_id_arg = None
    elif arg == "--customer-id" and customer_id_arg is None:
        customer_id_arg = None

if customer_id_arg is not None:
    set_current_customer(customer_id_arg)

window = Tk()

window.geometry("1035x534")
window.configure(bg = "#FFFFFF")

# Center the order window on the screen
try:
    window.update_idletasks()
    _w, _h = 1035, 534
    _sw = window.winfo_screenwidth()
    _sh = window.winfo_screenheight()
    _x = int((_sw - _w) / 2)
    _y = int((_sh - _h) / 2)
    window.geometry(f"{_w}x{_h}+{_x}+{_y}")
except Exception:
    pass


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 534,
    width = 1035,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    517.0,
    267.0,
    image=image_image_1
)

def open_coming_soon():
    try:
        subprocess.Popen([sys.executable, "-m", "app.ui.coming_soon"], cwd=str(PROJECT_ROOT))
    finally:
        try:
            window.destroy()
        except Exception:
            pass


def open_home():
    try:
        subprocess.Popen([sys.executable, "-m", "app.ui.home"], cwd=str(PROJECT_ROOT))
    finally:
        try:
            window.destroy()
        except Exception:
            pass


def open_options_popup(product_name=None):
    def handle_add_item(item):
        size = item.get("size", "Regular")
        qty = item.get("qty", 1)
        if product_name:
            try:
                if add_item_from_db(product_name, size=size, qty=qty):
                    render_cart()
                    return
            except Exception as exc:
                print(f"Failed to add product from database: {exc}")
        add_item_to_cart(item)

    try:
        show_options_popup(window, on_add_item=handle_add_item, product_name=product_name)
    except Exception as e:
        print(f"Failed to open options popup: {e}")

# -------------------- Cart/Order list state + rendering (shared) --------------------
# UI-only canvas ids used to clear/re-render image elements
cart_item_canvas_ids = []  # to clear and rerender item cards
cart_item_image_refs = []  # keep PhotoImage references alive for cart items
orders_history_window = None

subtotal_text_id = None
add_on_text_id = None
total_text_id = None

# Product data caches for dynamic menu rendering
_product_rows = []
_product_photo_refs = []
_category_names = []
_current_category_filter = "All"
def abbreviate_text(text, max_chars=24):
    try:
        if len(text) <= max_chars:
            return text
        return text[: max_chars - 1] + "…"
    except Exception:
        return text

def add_item_to_cart(item):
    try:
        add_item(item)
    except Exception:
        pass
    render_cart()

def change_item_qty_ui(index, delta):
    try:
        change_item_qty(index, delta)
    except Exception:
        pass
    render_cart()

def render_cart():
    # Always read latest shared state
    s = get_state()
    cart_items = s.get("cart_items", [])
    add_on = float(s.get("add_on_total_amount", 0.0))

    # Clear existing item drawings on the cart canvas
    for _id in cart_item_canvas_ids:
        try:
            cart_canvas.delete(_id)
        except Exception:
            pass
    cart_item_canvas_ids.clear()
    cart_item_image_refs.clear()

    # Local layout inside cart_canvas
    left_x = 10
    right_x = 215
    y = 0
    card_height = 70
    v_gap = 14

    # Draw each item card
    for idx, it in enumerate(cart_items):
        try:
            # background card
            bg = cart_canvas.create_rectangle(
                left_x, y, right_x, y + card_height, fill="#ECE3D1", outline="", width=0
            )
            cart_item_canvas_ids.append(bg)

            text_left = left_x + 16

            # Title: Name (Size)
            product_name = abbreviate_text(it.get("name"), 24)
            t1 = cart_canvas.create_text(
                text_left, y + 12, anchor="nw", text=product_name, fill="#1E1E1E",
                font=("Poppins SemiBold", 11 * -1)
            )
            cart_item_canvas_ids.append(t1)

            size_text = f"({it.get('size','Regular')})"
            t_size = cart_canvas.create_text(
                text_left, y + 28, anchor="nw", text=size_text, fill="#6C6C6C",
                font=("Poppins Regular", 10 * -1)
            )
            cart_item_canvas_ids.append(t_size)

            # Price on right
            price_str = f"₱{float(it.get('price',0)):.2f}"
            tprice = cart_canvas.create_text(
                right_x - 16, y + 12, anchor="ne", text=price_str, fill="#1E1E1E",
                font=("Poppins SemiBold", 12 * -1)
            )
            cart_item_canvas_ids.append(tprice)

            # Qty line like: "1  x  ₱29.00" in grey
            qty_line = f"{int(it.get('qty',1))}  x  ₱{float(it.get('price',0)):.2f}"
            t2 = cart_canvas.create_text(
                text_left, y + 44, anchor="nw", text=qty_line, fill="#9A9A9B",
                font=("Poppins Regular", 11 * -1)
            )
            cart_item_canvas_ids.append(t2)

            # Minus and plus simple circle buttons
            minus_circle = cart_canvas.create_oval(
                right_x - 64, y + 44, right_x - 40, y + 68, outline="#9A9A9B", width=2
            )
            minus_line = cart_canvas.create_line(
                right_x - 60, y + 56, right_x - 44, y + 56, fill="#9A9A9B", width=2
            )
            cart_item_canvas_ids.extend([minus_circle, minus_line])

            plus_circle = cart_canvas.create_oval(
                right_x - 32, y + 44, right_x - 8, y + 68, outline="#9A9A9B", width=2
            )
            plus_h = cart_canvas.create_line(
                right_x - 28, y + 56, right_x - 12, y + 56, fill="#9A9A9B", width=2
            )
            plus_v = cart_canvas.create_line(
                right_x - 20, y + 48, right_x - 20, y + 64, fill="#9A9A9B", width=2
            )
            cart_item_canvas_ids.extend([plus_circle, plus_h, plus_v])

            # Bind clicks to adjust qty
            def bind_click(tag_id, cb):
                cart_canvas.tag_bind(tag_id, "<Button-1>", lambda _e: cb())

            bind_click(minus_circle, lambda i=idx: change_item_qty_ui(i, -1))
            bind_click(minus_line,   lambda i=idx: change_item_qty_ui(i, -1))
            bind_click(plus_circle,  lambda i=idx: change_item_qty_ui(i, +1))
            bind_click(plus_h,       lambda i=idx: change_item_qty_ui(i, +1))
            bind_click(plus_v,       lambda i=idx: change_item_qty_ui(i, +1))

        except Exception:
            pass

        y += card_height + v_gap

    # Update scrollable area
    try:
        cart_canvas.configure(scrollregion=(0, 0, 225, y))
    except Exception:
        pass

    # Update totals
    try:
        subtotal = sum(float(it.get('price',0)) * int(it.get('qty',1)) for it in cart_items if not it.get('is_add_on'))
        total = subtotal + float(add_on)
        if subtotal_text_id is not None:
            canvas.itemconfigure(subtotal_text_id, text=f"₱{subtotal:.2f}")
        if add_on_text_id is not None:
            canvas.itemconfigure(add_on_text_id, text=f"₱{add_on:.2f}")
        if total_text_id is not None:
            canvas.itemconfigure(total_text_id, text=f"₱{total:.2f}")
    except Exception:
        pass

def clear_cart():
    try:
        shared_clear_cart()
    except Exception:
        pass
    render_cart()


def open_orders_history():
    global orders_history_window
    if orders_history_window and orders_history_window.winfo_exists():
        try:
            orders_history_window.lift()
            return
        except Exception:
            orders_history_window = None

    orders_history_window = Toplevel(window)
    orders_history_window.title("Order History")
    orders_history_window.geometry("720x420")
    orders_history_window.configure(bg="#FFF8E7")

    try:
        orders_history_window.transient(window)
        orders_history_window.grab_set()
    except Exception:
        pass

    try:
        orders_history_window.update_idletasks()
        w, h = 720, 420
        pw = window.winfo_width()
        ph = window.winfo_height()
        px = window.winfo_rootx()
        py = window.winfo_rooty()
        x = int(px + (pw - w) / 2)
        y = int(py + (ph - h) / 2)
        orders_history_window.geometry(f"{w}x{h}+{x}+{y}")
    except Exception:
        pass

    header = Label(
        orders_history_window,
        text="Order History",
        font=("Poppins Bold", 18),
        bg="#FFF8E7",
        fg="#4A3728",
    )
    header.pack(pady=(20, 10))

    from app.db.connection import db

    customer_id = get_state().get("customer_id")
    if not customer_id:
        info = Label(
            orders_history_window,
            text="No customer information available.\nPlease log in again.",
            font=("Poppins Regular", 12),
            bg="#FFF8E7",
            fg="#4A3728",
            justify="center",
        )
        info.pack(pady=10)
    else:
        orders = db.fetch_customer_orders(customer_id)
        if not orders:
            info = Label(
                orders_history_window,
                text="You have no recorded orders yet.\nPlace an order to see it listed here.",
                font=("Poppins Regular", 12),
                bg="#FFF8E7",
                fg="#4A3728",
                justify="center",
            )
            info.pack(pady=10)
        else:
            columns = ("order_id", "total", "payment", "date", "items")
            tree = ttk.Treeview(
                orders_history_window,
                columns=columns,
                show="headings",
                height=12,
            )
            tree.heading("order_id", text="Order ID")
            tree.heading("total", text="Total Amount")
            tree.heading("payment", text="Payment Method")
            tree.heading("date", text="Date")
            tree.heading("items", text="Items")

            tree.column("order_id", width=80, anchor="center")
            tree.column("total", width=120, anchor="center")
            tree.column("payment", width=160, anchor="center")
            tree.column("date", width=200, anchor="center")
            tree.column("items", width=420, anchor="w")

            for order in orders:
                sale_id = order.get("sale_id")
                items_description = ""
                if sale_id:
                    try:
                        items = db.fetch_sale_items(sale_id)
                        if items:
                            formatted_items = []
                            for item in items:
                                formatted_items.append(
                                    f"{item.get('name') or 'Item'} x{item.get('quantity', 0)} @ ₱{float(item.get('price') or 0.0):.2f}"
                                )
                            items_description = "; ".join(formatted_items)
                    except Exception:
                        items_description = ""
                tree.insert(
                    "",
                    "end",
                    values=(
                        order.get("sale_id"),
                        f"₱{float(order.get('total_amount') or 0.0):,.2f}",
                        str(order.get("payment_method") or "").title(),
                        str(order.get("sale_date") or ""),
                        items_description,
                    ),
                )

            x_scroll = ttk.Scrollbar(
                orders_history_window, orient="horizontal", command=tree.xview
            )
            tree.configure(xscrollcommand=x_scroll.set)
            tree.pack(fill="both", expand=True, padx=20, pady=(10, 0))
            x_scroll.pack(fill="x", padx=20, pady=(0, 20))

    close_btn = Button(
        orders_history_window,
        text="Close",
        font=("Poppins", 11, "bold"),
        bg="#B96708",
        fg="white",
        relief="flat",
        width=12,
        command=orders_history_window.destroy,
    )
    close_btn.pack(pady=(0, 20))

    orders_history_window.resizable(False, False)

def open_checkout_popup():
    try:
        payload = export_for_checkout()
        if not payload:
            messagebox.showinfo("Checkout", "Your cart is empty.")
            return

        cart_items = payload.get("items") if isinstance(payload, dict) else payload
        if not cart_items:
            messagebox.showinfo("Checkout", "Your cart is empty.")
            return

        add_on_total = float(payload.get("add_on_total", 0.0)) if isinstance(payload, dict) else 0.0
        customer_id = payload.get("customer_id") if isinstance(payload, dict) else None
        if customer_id is not None:
            set_current_customer(customer_id)

        run_checkout(cart_items, parent=window, add_on_total=add_on_total, customer_id=customer_id)
    except Exception as exc:
        print(f"Failed to open checkout popup: {exc}")
        messagebox.showerror("Checkout", f"Unable to open checkout window:\n{exc}")
    finally:
        try:
            render_cart()
        except Exception:
            pass

canvas.create_rectangle(
    0.0,
    57.0,
    1035.0,
    535.0,
    fill="#EFE8D8",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1035.0,
    57.0,
    fill="#B96708",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_home,
    relief="flat"
)
button_1.place(
    x=944.0,
    y=0.0,
    width=46.0,
    height=46.0
)

try:
    orders_icon_image = PhotoImage(file=relative_to_assets("orders_icon.png"))
except Exception:
    orders_icon_image = PhotoImage(width=46, height=46)
    orders_icon_image.put("#B96708", to=(0, 0, 46, 46))
    orders_icon_image.put("#FFFFFF", to=(10, 12, 36, 16))
    orders_icon_image.put("#FFFFFF", to=(10, 21, 36, 25))
    orders_icon_image.put("#FFFFFF", to=(10, 30, 36, 34))
orders_icon_button = Button(
    image=orders_icon_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_orders_history(),
    relief="flat",
    bg="#B96708",
    activebackground="#B96708",
)
orders_icon_button.place(
    x=888.0,
    y=0.0,
    width=46.0,
    height=46.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    87.0,
    24.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    274.0,
    24.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF8E7",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=179.0,
    y=12.0,
    width=190.0,
    height=22.0
)

canvas.create_rectangle(
    34.0,
    75.0,
    236.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    135.0,
    288.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    501.0,
    287.0,
    image=image_image_4
)

canvas.create_text(
    58.0,
    81.0,
    anchor="nw",
    text="Menu",
    fill="#B96708",
    font=("Poppins ExtraBold", 32 * -1)
)

category_title_id = canvas.create_text(
    268.0,
    90.0,
    anchor="nw",
    text="All Products",
    fill="#B96708",
    font=("Poppins Bold", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Praf", refresh=True),
    relief="flat"
)
button_2.place(
    x=51.0,
    y=241.0,
    width=171.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Milk Tea", refresh=True),
    relief="flat"
)
button_3.place(
    x=49.0,
    y=189.0,
    width=171.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("All", refresh=True),
    relief="flat"
)
button_4.place(
    x=49.0,
    y=136.0,
    width=171.0,
    height=36.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Fruit Tea", refresh=True),
    relief="flat"
)
button_5.place(
    x=51.0,
    y=290.0,
    width=171.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Coffee", refresh=True),
    relief="flat"
)
button_6.place(
    x=51.0,
    y=338.0,
    width=171.0,
    height=36.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Brosty", refresh=True),
    relief="flat"
)
button_7.place(
    x=51.0,
    y=387.0,
    width=171.0,
    height=35.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: filter_products("Add-On", refresh=True),
    relief="flat"
)
button_8.place(
    x=51.0,
    y=435.0,
    width=171.0,
    height=35.0
)

# ------------------------------------------------------------------
# Dynamic products grid setup
# ------------------------------------------------------------------
products_container = Frame(window, bg="#EFE8D8")
products_container.place(x=258, y=120, width=500, height=360)

products_scrollbar = Scrollbar(products_container, orient="vertical")
products_scrollbar.pack(side="right", fill="y")

products_canvas = Canvas(
    products_container,
    bg="#EFE8D8",
    bd=0,
    highlightthickness=0,
    yscrollcommand=products_scrollbar.set,
)
products_canvas.pack(side="left", fill="both", expand=True)
products_scrollbar.config(command=products_canvas.yview)

products_inner_frame = Frame(products_canvas, bg="#EFE8D8")
products_canvas.create_window((0, 0), window=products_inner_frame, anchor="nw")


def _on_products_config(_event=None):
    try:
        products_canvas.configure(scrollregion=products_canvas.bbox("all"))
    except Exception:
        pass


products_inner_frame.bind("<Configure>", _on_products_config)


def _load_products_from_db():
    """Fetch products from the database for display."""
    global _product_rows, _category_names, _current_category_filter
    try:
        raw_products = ProductRepository.get_all_products()
    except Exception as exc:
        print(f"Failed to load products for order screen: {exc}")
        raw_products = []

    formatted = []
    categories = set()
    for product in raw_products:
        name = (
            product.get("product_name")
            or product.get("name")
            or product.get("product_code")
            or "Unnamed Product"
        )
        category = (
            product.get("category_name")
            or product.get("category")
            or "Uncategorized"
        )
        price_regular = float(product.get("price_regular") or product.get("price") or 0.0)
        price_large = float(product.get("price_large") or price_regular)
        formatted.append(
            {
                "product_id": product.get("product_id"),
                "name": name,
                "category": category,
                "price_regular": price_regular,
                "price_large": price_large,
                "image_path": product.get("image_path"),
                "image_blob": product.get("image_blob"),
            }
        )
        categories.add(category)

    _product_rows = formatted
    _category_names = sorted(categories, key=lambda x: x.lower()) if categories else []
    if _current_category_filter != "All":
        if not any(
            c.lower() == _current_category_filter.lower() for c in ["All"] + _category_names
        ):
            _current_category_filter = "All"


def _create_product_photo(product: dict):
    """Return a PhotoImage for the given product."""
    photo = None
    blob = product.get("image_blob")
    if blob:
        try:
            encoded = base64.b64encode(blob).decode("ascii")
            photo = PhotoImage(data="base64," + encoded)
        except Exception:
            photo = None
    if photo is None:
        image_path = product.get("image_path")
        if image_path and os.path.exists(image_path):
            try:
                photo = PhotoImage(file=image_path)
            except Exception:
                photo = None
    if photo is not None:
        _product_photo_refs.append(photo)
    return photo


def render_products(category_filter="All"):
    """Render product grid for the specified category."""
    global _current_category_filter
    _current_category_filter = category_filter or "All"
    for child in products_inner_frame.winfo_children():
        child.destroy()
    _product_photo_refs.clear()

    if not _product_rows:
        Label(
            products_inner_frame,
            text="No products available.",
            bg="#EFE8D8",
            fg="#4A3728",
            font=("Poppins", 12, "italic"),
        ).pack(pady=20)
        products_canvas.yview_moveto(0)
        canvas.itemconfigure(
            category_title_id,
            text="All Products" if _current_category_filter == "All" else _current_category_filter,
        )
        return

    def matches_category(product: dict) -> bool:
        if _current_category_filter == "All":
            return True
        return product.get("category", "").lower() == _current_category_filter.lower()

    filtered = [prod for prod in _product_rows if matches_category(prod)]

    if not filtered:
        Label(
            products_inner_frame,
            text="No products in this category.",
            bg="#EFE8D8",
            fg="#4A3728",
            font=("Poppins", 12, "italic"),
        ).pack(pady=20)
        products_canvas.yview_moveto(0)
    else:
        columns = 4
        for index, product in enumerate(filtered):
            row = index // columns
            col = index % columns
            card = Frame(products_inner_frame, bg="#EFE8D8", bd=0)
            card.grid(row=row, column=col, padx=10, pady=10, sticky="n")

            photo = _create_product_photo(product)
            if photo is not None:
                image_label = Label(card, image=photo, bg="#EFE8D8")
                image_label.pack(pady=(0, 6))
            else:
                name_label = Label(
                    card,
                    text=product["name"],
                    bg="#EFE8D8",
                    fg="#4A3728",
                    font=("Poppins", 11, "bold"),
                    wraplength=120,
                    justify="center",
                )
                name_label.pack(pady=(4, 2))

                price_text = f"₱{product['price_regular']:.2f}"
                if product["price_large"] and abs(product["price_large"] - product["price_regular"]) > 0.01:
                    price_text += f" / ₱{product['price_large']:.2f}"
                price_label = Label(
                    card,
                    text=price_text,
                    bg="#EFE8D8",
                    fg="#1E8449",
                    font=("Poppins", 10),
                )
                price_label.pack(pady=(0, 2))

                status_label = Label(
                    card,
                    text="Available",
                    bg="#EFE8D8",
                    fg="#1C9C5B",
                    font=("Poppins", 10),
                )
                status_label.pack(pady=(0, 6))

            order_button = Button(
                card,
                text="Order",
                font=("Poppins", 9, "bold"),
                bg="#B96708",
                fg="white",
                relief="flat",
                command=lambda name=product["name"]: open_options_popup(name),
            )
            order_button.pack(pady=(6, 0))

    products_canvas.yview_moveto(0)
    canvas.itemconfigure(
        category_title_id,
        text="All Products" if _current_category_filter == "All" else _current_category_filter,
    )


def filter_products(category_name="All", refresh=False):
    """Filter products by category, optionally refreshing from the database."""
    if refresh or not _product_rows:
        _load_products_from_db()
    render_products(category_name or "All")

canvas.create_rectangle(
    768.0,
    75.0,
    1005.0,
    502.0,
    fill="#EFE8D8",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    886.0,
    288.0,
    image=image_image_5
)

# --- Scrollable cart area (only for cart items; totals remain fixed) ---
cart_container = Frame(window, bg="#EFE8D8")
cart_container.place(x=772, y=120, width=225, height=220)

cart_scrollbar = Scrollbar(cart_container, orient="vertical")
cart_scrollbar.pack(side="right", fill="y")

cart_canvas = Canvas(
    cart_container,
    bg="#EFE8D8",
    bd=0,
    highlightthickness=0,
    yscrollcommand=cart_scrollbar.set,
)
cart_canvas.pack(side="left", fill="both", expand=True)
cart_scrollbar.config(command=cart_canvas.yview)

def _on_cart_mousewheel(event):
    try:
        cart_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
    except Exception:
        pass

def _bind_cart_wheel(_event=None):
    try:
        cart_canvas.bind_all("<MouseWheel>", _on_cart_mousewheel)
    except Exception:
        pass

def _unbind_cart_wheel(_event=None):
    try:
        cart_canvas.unbind_all("<MouseWheel>")
    except Exception:
        pass

cart_canvas.bind("<Enter>", _bind_cart_wheel)
cart_canvas.bind("<Leave>", _unbind_cart_wheel)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=clear_cart,
    relief="flat"
)
button_9.place(
    x=788.911865234375,
    y=447.12646484375,
    width=90.61764526367188,
    height=39.73057174682617
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=open_checkout_popup,
    relief="flat"
)
button_10.place(
    x=893.470703125,
    y=447.12646484375,
    width=93.60504150390625,
    height=39.73057174682617
)

# Add-On label remains same
canvas.create_text(
    796.878173828125,
    372.86761474609375,
    anchor="nw",
    text="Add-On",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

add_on_text_id = canvas.create_text(
    936.0,
    371.0,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    353.0023193359375,
    anchor="nw",
    text="SubTotal",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

subtotal_text_id = canvas.create_text(
    936.2900390625,
    350.3536376953125,
    anchor="nw",
    text="₱0.00",
    fill="#9A9A9B",
    font=("Poppins Regular", 12 * -1)
)

total_text_id = canvas.create_text(
    936.2900390625,
    414.5302734375,
    anchor="nw",
    text="₱0.00",
    fill="#1E1E1E",
    font=("Poppins SemiBold", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    793.890869140625,
    390.525634765625,
    anchor="nw",
    text="-----------------------------------",
    fill="#9A9B9C",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    796.878173828125,
    412.59820556640625,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("Poppins SemiBold", 12 * -1)
)

search_listbox = Listbox(window)
search_listbox.place(x=179.0, y=34.0, width=190.0, height=0)
search_listbox.place_forget()

_current_suggestions = []

def _hide_suggestions():
    try:
        search_listbox.place_forget()
    except Exception:
        pass

def _show_suggestions_if_any():
    if _current_suggestions:
        # Adjust height based on items (max 6 visible)
        visible = min(len(_current_suggestions), 6)
        try:
            search_listbox.place(x=179.0, y=34.0, width=190.0, height=visible * 18)
        except Exception:
            pass
    else:
        _hide_suggestions()

def _on_search_change(_evt=None):
    query = entry_1.get().strip().lower()
    _current_suggestions.clear()
    search_listbox.delete(0, "end")
    if not query:
        _hide_suggestions()
        return
    if not _product_rows:
        return
    for product in _product_rows:
        name = product.get("name", "")
        if query in name.lower():
            _current_suggestions.append(product)
            search_listbox.insert("end", name)
    _show_suggestions_if_any()

def _on_suggestion_select(_evt=None):
    if not _current_suggestions:
        return
    try:
        sel = search_listbox.curselection()
        if not sel:
            return
        idx = sel[0]
        prod = _current_suggestions[idx]
        open_options_popup(prod.get("name"))
    finally:
        _hide_suggestions()

entry_1.bind("<KeyRelease>", _on_search_change)
search_listbox.bind("<<ListboxSelect>>", _on_suggestion_select)

# Initial product load
filter_products("All", refresh=True)

canvas.create_rectangle(
    734.0,
    132.0,
    746.0,
    196.0,
    fill="#000000",
    outline="")
try:
    render_cart()
except Exception:
    pass

window.resizable(False, False)
window.mainloop()

