# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox
from app.services.utils import UtilityFunctions
import mysql.connector
import sys
import os

OUTPUT_PATH = Path(__file__).parent

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def relative_to_assets(path: str) -> Path:
    """Get path to assets in the resetpass resources folder"""
    possible_paths = [
        resource_path(f"resources/resetpass/{path}"),
        resource_path(f"resetpass/resources/{path}"),
        os.path.join(OUTPUT_PATH, "resources", "resetpass", path),
        os.path.join(OUTPUT_PATH, "resetpass", "resources", path),
        resource_path(path),
    ]
    
    for asset_path in possible_paths:
        if os.path.exists(asset_path):
            return Path(asset_path)
    
    # If no path found, return the most likely one
    return Path(possible_paths[0])

class PasswordResetWindow:
    def __init__(self, parent, user_email, show_login_callback, get_db_connection):
        self.parent = parent
        self.user_email = user_email
        self.show_login_callback = show_login_callback
        self.get_db_connection = get_db_connection
        self.images = []  # Keep references to images
        
        self.setup_ui()
        
    def load_image(self, path: str):
        """Load image and keep reference to prevent garbage collection"""
        try:
            image_path = relative_to_assets(path)
            if not image_path.exists():
                print(f"Image not found: {image_path}")
                return None
            photo_image = PhotoImage(file=image_path)
            self.images.append(photo_image)
            return photo_image
        except Exception as e:
            print(f"Error loading image {path}: {e}")
            return None
        
    def setup_ui(self):
        """Setup the password reset UI"""
        # Clear any existing widgets first
        for widget in self.parent.winfo_children():
            widget.destroy()
        
        # Create canvas
        self.canvas = Canvas(
            self.parent,
            bg="#FFFFFF",
            height=440,
            width=800,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)
        
        # Load background image
        image_image_1 = self.load_image("image_1.png")
        if image_image_1:
            self.canvas.create_image(400.0, 220.0, image=image_image_1)

        # Background rectangle
        self.canvas.create_rectangle(
            49.0,
            87.0,
            316.0,
            276.0,
            fill="#3A280F",
            outline=""
        )

        # Reset password button
        button_image_1 = self.load_image("button_resetpass.png")
        if button_image_1:
            self.button_resetpass = Button(
                image=button_image_1,
                borderwidth=0,
                highlightthickness=0,
                command=self.reset_password,
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_resetpass = Button(
                text="Reset Password",
                borderwidth=0,
                highlightthickness=0,
                command=self.reset_password,
                relief="flat",
                bg="#D2691E",
                fg="#FFFFFF",
                cursor="hand2"
            )
        self.button_resetpass.place(x=54.0, y=323.0, width=245.0, height=42.0)

        # New password entry
        entry_image_1 = self.load_image("entry_newpass.png")
        if entry_image_1:
            self.canvas.create_image(177.5, 174.0, image=entry_image_1)
            
        self.entry_newpass = Entry(
            bd=0,
            bg="#FFF8E7",
            fg="#000716",
            highlightthickness=0,
            show="●",
            font=("Inter", 12)
        )
        self.entry_newpass.place(x=63.0, y=154.0, width=229.0, height=38.0)
        self.entry_newpass.bind('<Return>', lambda e: self.entry_confirmpass.focus())

        # Confirm password entry
        entry_image_2 = self.load_image("entry_confirmpass.png")
        if entry_image_2:
            self.canvas.create_image(178.5, 225.0, image=entry_image_2)
            
        self.entry_confirmpass = Entry(
            bd=0,
            bg="#FFF8E7",
            fg="#000716",
            highlightthickness=0,
            show="●",
            font=("Inter", 12)
        )
        self.entry_confirmpass.place(x=64.0, y=205.0, width=229.0, height=38.0)
        self.entry_confirmpass.bind('<Return>', lambda e: self.reset_password())

        # First eye button (for new password)
        button_image_2 = self.load_image("button_eye.png")
        if button_image_2:
            self.button_eye_new = Button(
                image=button_image_2,
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_newpass),
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_eye_new = Button(
                text="👁",
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_newpass),
                relief="flat",
                cursor="hand2"
            )
        self.button_eye_new.place(x=272.0, y=164.0, width=20.0, height=19.0)

        # Second eye button (for confirm password)
        button_image_3 = self.load_image("button_eye.png")
        if button_image_3:
            self.button_eye_confirm = Button(
                image=button_image_3,
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_confirmpass),
                relief="flat",
                cursor="hand2"
            )
        else:
            self.button_eye_confirm = Button(
                text="👁",
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.toggle_password_visibility(self.entry_confirmpass),
                relief="flat",
                cursor="hand2"
            )
        self.button_eye_confirm.place(x=272.0, y=217.0, width=20.0, height=19.0)

        # Title text
        self.canvas.create_text(
            38.0,
            87.0,
            anchor="nw",
            text="Reset Password",
            fill="#FFFFFF",
            font=("Inter Bold", 36 * -1)
        )

        # # Subtitle text
        # self.canvas.create_text(
        #     38.0,
        #     125.0,
        #     anchor="nw",
        #     text=f"Create a new password for {self.user_email}",
        #     fill="#FFFFFF",
        #     font=("Inter", 12)
        # )

        # Set explicit tab order for proper keyboard navigation
        self.entry_newpass.lift()  # Ensure new password entry is on top
        self.entry_confirmpass.lift()
        self.button_resetpass.lift()
        
        # Ensure eye buttons are visible
        self.button_eye_new.lift()
        self.button_eye_confirm.lift()
        
        # Configure tab order explicitly
        self.entry_newpass.tk_focusNext = lambda: self.entry_confirmpass
        self.entry_confirmpass.tk_focusNext = lambda: self.button_resetpass
        self.button_resetpass.tk_focusNext = lambda: self.entry_newpass
        
        # Back button - create after all other elements
        try:
            button_back_1 = PhotoImage(
                file=relative_to_assets("button_back.png"))
            button_back = Button(
                image=button_back_1,
                borderwidth=0,
                highlightthickness=0,
                command=self.go_back,
                relief="flat",
                cursor="hand2"
            )
            button_back.place(
                x=10.0,
                y=10.0,
                width=30.0,
                height=30.0
            )
            # Ensure back button is on top of all other elements
            button_back.lift()
            # Store reference to prevent garbage collection
            self.button_back_image = button_back_1
        except Exception as e:
            print(f"Error loading back button image: {e}")
            # Fallback: create text button if image fails
            button_back = Button(
                text="←",
                borderwidth=0,
                highlightthickness=0,
                command=self.go_back,
                relief="flat",
                cursor="hand2",
                bg="#3A280F",
                fg="#FFFFFF",
                font=("Arial", 12, "bold")
            )
            button_back.place(
                x=10.0,
                y=10.0,
                width=30.0,
                height=30.0
            )
            button_back.lift()

        # Set focus to new password entry
        self.entry_newpass.focus()

    def toggle_password_visibility(self, entry_widget):
        """Toggle the visibility of the password field"""
        if entry_widget.cget('show') == "●":
            entry_widget.config(show="")
        else:
            entry_widget.config(show="●")

    def reset_password(self):
        """Reset the user's password"""
        new_password = self.entry_newpass.get().strip()
        confirm_password = self.entry_confirmpass.get().strip()

        if not new_password or not confirm_password:
            messagebox.showerror("Error", "Please fill in both password fields")
            return

        if new_password != confirm_password:
            messagebox.showerror("Error", "Passwords do not match")
            return

        if len(new_password) < 6:
            messagebox.showerror("Error", "Password must be at least 6 characters long")
            return
        
        # Additional password strength validation
        if not any(c.isupper() for c in new_password):
            messagebox.showerror("Error", "Password must contain at least one uppercase letter")
            return
            
        if not any(c.isdigit() for c in new_password):
            messagebox.showerror("Error", "Password must contain at least one number")
            return

        db_connection = self.get_db_connection()
        if not db_connection:
            messagebox.showerror("Database Error", "Cannot connect to database")
            return

        try:
            cursor = db_connection.cursor(dictionary=True)
            
            # First verify the customer exists and is active
            cursor.execute(
                "SELECT customer_id, email FROM customers WHERE email = %s AND is_active = 1",
                (self.user_email,)
            )
            customer = cursor.fetchone()
            
            if not customer:
                messagebox.showerror("Error", "Customer account not found or inactive")
                return
            
            # Hash the new password
            hashed_password = UtilityFunctions.hash_password(new_password)
            
            # Update the customer's password
            cursor.execute(
                "UPDATE customers SET password_hash = %s, updated_at = NOW() WHERE email = %s",
                (hashed_password, self.user_email)
            )
            
            if cursor.rowcount == 0:
                messagebox.showerror("Error", "Failed to reset password. Please try again.")
                return
                
            db_connection.commit()
            
            # Show success message with customer details
            success_message = f"""
            ✅ Password Reset Successful!
            
            Your BigBrew Coffee Shop account password has been updated.
            
            Account Details:
            • Email: {self.user_email}
            • Customer ID: {customer['customer_id']}
            
            You can now login with your new password.
            """
            
            messagebox.showinfo("Success", success_message.strip())
            self.show_login_callback()
            
        except mysql.connector.Error as e:
            messagebox.showerror("Database Error", f"Failed to reset password: {str(e)}")
            try:
                db_connection.rollback()
            except:
                pass
        except Exception as e:
            messagebox.showerror("Error", f"An unexpected error occurred: {str(e)}")
            try:
                db_connection.rollback()
            except:
                pass
        finally:
            if db_connection and db_connection.is_connected():
                cursor.close()

    def go_back(self):
        """Go back to login screen"""
        self.destroy()
        self.show_login_callback()

    def destroy(self):
        """Clean up the window"""
        for widget in self.parent.winfo_children():
            widget.destroy()

